<?php
/**
 * Vue pour un document dans l'état initial
 */
?>

<?php include __DIR__ . '/../common/document-header.phtml';?>

<?php $message = Halms_Document_Logger::getLastComment($this->document->getDocid(), Halms_Document::STATUS_INITIAL_READY);
if ($message != '') { ?>
    <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>
            <i class="glyphicon glyphicon-info-sign"></i>&nbsp;
            <?php echo $message;?>
        </strong>
    </div>
<?php } ?>
<h4><?php echo $this->translate('Contenu du package'); ?></h4>
<table class="table table-hover">
    <tbody class="listfiles">
    <?php
    foreach($this->dirContent as $key => $files) {
        if (! is_array($files)) {
            $files = [$files];
            $showIndex = false;
        } else {
            $showIndex = true;
        }
        $index = 0;
        foreach($files as $file) {
            $index++;
            ?>
            <tr style="height:40px;">
                <td style="width:100px"><strong><?php echo $key ?></strong></td>
                <td style="width:50px"><?php echo $showIndex ? $index : '';?></td>
                <td>
                    <a href="/file/package/docid/<?php echo $this->document->getDocid();?>/filename/<?php echo $file;?>?<?php echo rand(0,9999);?>" target="_blank"><i class="glyphicon glyphicon-file"></i>&nbsp;<?php echo $file ?></a>
                    <?php if ($key == 'Meta') {?>
                        <div class="btn-group btn-group-xs" role="group">
                            <form action="/administrate/index" method="post" class="form-inline" style="display:inline-block;">
                                <input type="hidden" name="docid" value="<?php echo $this->document->getDocid();?>" />
                                <input type="hidden" name="refreshxml" value="1" />
                                <button type="submit" class="btn btn-default btn-xs"><i class="glyphicon glyphicon-refresh"></i>&nbsp;<?php echo $this->translate('Regénérer'); ?></button>
                            </form>
                        </div>
                    <?php } else { ?>
                        <div class="btn-group btn-group-xs" role="group">
                            <?php if ($key != 'PDF') { ?>
                            <form action="/administrate/index" method="post" class="form-inline" style="float:left;">
                                <input type="hidden" name="docid" value="<?php echo $this->document->getDocid();?>" />
                                <input type="hidden" name="delfile" value="<?php echo $file ;?>" />
                                <button type="submit" class="btn btn-default btn-xs"><i class="glyphicon glyphicon-trash"></i>&nbsp;<?php echo $this->translate('Supprimer'); ?></button>
                            </form>
                            <?php } ?>
                            <form action="/administrate/index" method="post" enctype="multipart/form-data" class="form-inline" style="float:left;">
                                <input type="hidden" name="docid" value="<?php echo $this->document->getDocid();?>" />
                                <input type="hidden" name="oldfile" value="<?php echo $file;?>" />
                                <input type="file" name="files[]" style="display:none;"/>
                                <div class="btn-group" role="group">
                                    <button type="button" class="btn btn-default btn-xs select-files"><i class="glyphicon glyphicon-folder-open"></i>&nbsp;<?php echo $this->translate('Remplacer par...'); ?></button>
                                </div>
                            </form>
                        </div>
                    <?php } ?>
                </td>
            </tr>
            <?php
        }
    } ?>
        <tr style="height:40px;">
            <td><strong>Annex</strong></td>
            <td></td>
            <td>
                <form action="/administrate/index" method="post" enctype="multipart/form-data" class="form-inline" >
                    <input type="hidden" name="docid" value="<?php echo $this->document->getDocid();?>" />
                    <input type="file" multiple name="files[]" style="display:none;"/>
                    <div class="btn-group" role="group" style="display:inline-block;">
                        <button type="button" class="btn btn-default btn-xs select-files"><i class="glyphicon glyphicon-folder-open"></i>&nbsp;<?php echo $this->translate('Ajouter des fichiers ...'); ?></button>
                    </div>
                </form>
            </td>
        </tr>
    </tbody>
</table>
<form action="/administrate/index" method="post" id="form">
    <input type="hidden" name="docid" value="<?php echo $this->document->getDocid();?>" />
    <input type="hidden" name="newstatus" id="status" value="<?php echo Halms_Document::STATUS_WAIT_FOR_DCL?>" />
    <div class="well text-center" style="background-color: #f5f5f5;">
        <div class="btn-group btn-group">
            <button type="submit" class="btn btn-primary btn-action" id="btn-submit" attr-action="<?php echo Halms_Document::STATUS_WAIT_FOR_DCL?>">
                <i class="glyphicon glyphicon-export"></i>&nbsp;<?php echo $this->translate('Envoyer chez DCL'); ?>
            </button>
            <button type="submit" class="btn btn-default btn-action" attr-action="<?php echo Halms_Document::STATUS_INITIAL?>">
                <i class="glyphicon glyphicon-refresh"></i>&nbsp;<?php echo $this->translate('Remettre au statut initial'); ?>
            </button>
        </div>
        <div class="btn-group btn-group">
            <a  class="btn btn-default btn-action" href="/administrate">
                <i class="glyphicon glyphicon-chevron-left"></i>&nbsp;<?php echo $this->translate('Retour'); ?>
            </a>
        </div>
    </div>
</form>

<script type="text/javascript">
    $(function() {
        $('#form button').click(function(){
                $('#status').val($(this).attr('attr-action'));}
        );
        $('.select-files').click(function() {
            $(this).closest('form').find('input[type="file"]').click();
        });
        $('input[type="file"]').change(function() {
            $(this).closest('form').submit();
        });
    });
</script>