<?php
/**
 * Vue pour un document dans l'état initial
 */
?>

<?php include __DIR__ . '/../common/document-header.phtml';?>

<?php include __DIR__ . '/../../../../application/views/scripts/document/admin.phtml';?>

<hr/>
<form action="/administrate/index" method="post" id="form">
    <input type="hidden" name="docid" value="<?php echo $this->document->getDocid();?>" />
    <input type="hidden" name="newstatus" id="status" value="" />
    <div class="well text-center" style="background-color: #f5f5f5;">
        <textarea name="comment" class="form-control" rows="2" cols="20" placeholder="<?php echo $this->translate('Commentaire'); ?>" style="width:600px;margin:0 auto 20px;"></textarea>
        <div class="btn-group btn-group">
            <button type="submit" class="btn btn-primary btn-action" attr-action="<?php echo Halms_Document::STATUS_INITIAL_READY?>">
                <i class="glyphicon glyphicon-ok"></i>&nbsp;<?php echo $this->translate('Prêt pour DCL'); ?>
            </button>
            <button type="submit" class="btn btn-default btn-action" attr-action="<?php echo Halms_Document::STATUS_INITIAL_BLOCKED?>">
                <i class="glyphicon glyphicon-remove"></i>&nbsp;<?php echo $this->translate('Bloquer le dépôt'); ?>
            </button>
            <button type="submit" class="btn btn-default btn-action" attr-action="<?php echo Halms_Document::STATUS_INITIAL_AHEADOFPRINT?>">
                <i class="glyphicon glyphicon-tag"></i>&nbsp;<?php echo $this->translate('Ahead of print'); ?>
            </button>
            <button type="submit" class="btn btn-default btn-action" attr-action="<?php echo Halms_Document::STATUS_INITIAL_EMBARGO?>">
                <i class="glyphicon glyphicon-calendar"></i>&nbsp;<?php echo $this->translate('Mettre sous embargo'); ?>
            </button>
            <button type="submit" class="btn btn-default btn-action" attr-action="<?php echo Halms_Document::STATUS_INITIAL_UNKNOWN?>">
                <i class="glyphicon glyphicon-trash"></i>&nbsp;<?php echo $this->translate('Refuser le dépôt'); ?>
            </button>
        </div>
        <div class="btn-group btn-group">
            <a class="btn btn-default btn-action" href="/administrate">
                <i class="glyphicon glyphicon-chevron-left"></i>&nbsp;<?php echo $this->translate('Retour'); ?>
            </a>
        </div>
    </div>
</form>

<script type="text/javascript">
    $(function() {
        $('#form button').click(function(){
                $('#status').val($(this).attr('attr-action'));}
        );
    });
</script>