<?php
$this->jQuery()->addJavascriptFile("/js/document/evaluation.js");
$this->jQuery()->addJavascriptFile("/js/document/document.js");
$this->responsesContent = '';
$this->showHistory = true;
$this->moderate = true;
?>


<form action="<?php echo $this->formAction; ?>" method="post" id="evaluate-form">

<?php
foreach ( $this->docids as $docid ) {
	$this->document->setDocid ( $docid );
	$this->document->load ('',true);
	include __DIR__ . "/documents-document.phtml";
}


?>

<div class="form-actions text-center">
		<select class="form-control" id="evaluation-msg">
			<option value=""><?php echo $this->translate('Réponses prédéfinies'); ?></option>
        <?php
								
foreach ( $this->responses as $message ) {
									$array = $message->toArray ();
									$this->responsesContent .= '<div id="msg-' . $array ['messageid'] . '">' . $array ['message'] . '</div>';
									?>
            <option value="<?php echo $array['messageid'] ?>"><?php echo $array['title'] ?></option>
            <?php
								}
								?>
    </select><br />
		<textarea name="comment" id="comment" class="form-control" rows="3"></textarea>
		<br /> <input type="hidden" name="evaluate-action"
			id="evaluate-action" value="" />
		<div class="btn-group btn-group">

				
					<button type="button" class="btn btn-default btn-action" attr-action="moderation">
					<i class="glyphicon glyphicon-eye-open"></i>&nbsp;
					<?php echo $this->translate('Remettre en modération'); ?>
					</button>
   

			<?php if ($this->document->getStatus () != Hal_Document::STATUS_VALIDATE) : ?>
				<?php if ($this->document->getStatus () != Hal_Document::STATUS_MODIFICATION) : ?>
					<button type="button" class="btn btn-default btn-action" attr-action="update">
					<i class="glyphicon glyphicon-send"></i>&nbsp;
					<?php echo $this->translate('Demander une modification'); ?>
					</button>
				<?php else : ?>
				<button type="button" class="btn btn-warning btn-action" attr-action="update">
					<i class="glyphicon glyphicon-send"></i>&nbsp;
					<?php  echo $this->translate("Relancer la demande de modification"); ?>
					</button>
				<?php endif; ?>
			<?php endif; ?>
			
			<?php //juste pour un doc à la fois ?>
			<?php if ( count($this->docids) == 1) :?>			
			
				<?php if ($this->document->getStatus () == Hal_Document::STATUS_VALIDATE) : ?>
				<button type="button" class="btn btn-default btn-action" attr-action="validate">
				<i class="glyphicon glyphicon-eye-close"></i>&nbsp;
				<?php echo $this->translate("Modifier l'expertise..."); ?>
				</button>
				
				<button type="button" class="btn btn-warning btn-action" attr-action="validate-reminder">
				<i class="glyphicon glyphicon-eye-close"></i>&nbsp;
				<?php echo $this->translate('Relancer les experts'); ?>
				</button>
				<?php endif; ?>
				
				
			<?php endif; ?>
				
		
			<button type="button" class="btn btn-default btn-action"
				attr-action="delete">
				<i class="glyphicon glyphicon-trash"></i>&nbsp;<?php echo $this->translate('Supprimer'); ?></button>
				
				
			<button type="button" class="btn btn-default btn-action"
				attr-action="back">
				<i class="glyphicon glyphicon-arrow-left"></i>&nbsp;<?php echo $this->translate('Retour'); ?></button>
		</div>
		<div style="display: none">
        <?php echo $this->responsesContent?>
		</div>
	</div>


	<div id="expert-select-form"></div>


</form>


<script>

$(document).ready(function() {

    $('.btn-action').click(function() {

    	var action = $(this).attr('attr-action');
    	
		
    	var docid    = <?php echo $this->document->getDocid(); ?>;
		var sid      = <?php echo $this->document->getSid(); ?>;
		var domains  = <?php echo json_encode($this->document->getMeta('domain')); ?>;
		var typdoc   = '<?php echo $this->document->getTypDoc(); ?>';
		var forwardAction  = '<?php echo $this->forwardAction; ?>';
		var sourceController   = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>';
   	
    	
		if (action ==  'validate') {
			getExpertSelectForm(docid, sid, domains, typdoc, forwardAction, sourceController);
			return;
		}
        
        var cansubmit = true;
        
        if ( action == 'deleted' && $('#comment').val() == '') {
            cansubmit = false;
        }
        if (cansubmit) {
            $('#evaluate-action').val($(this).attr('attr-action'));
            $('#evaluate-form').submit();
        } else {

        }
    });
});


</script>