<?php
/** @var Hal_View $this */
$style = new Hal_Website_Style();
$this->containerClass = $style->getContainerClass();
$this->navigation = $style->getNavigationOrientation();
$this->cssFile = $style->getCssFile();

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

if ($this->document) {
    // used by tracker
    $documentid = '' . $this->document->getId();
    $docuri = $this->document->getUri();
    $docurlmainfile = $this->document->getUrlMainFile();
    $defaultFile =  $this->document->getDefaultFile();
    if ($defaultFile) {
        $docdefault = $defaultFile->getName();
    }
} else {
    $documentid = '';
    $docuri = '';
    $docuri = '';
    $docdefault = '';
}

if ( $controller == 'view' ) {
    echo $this->doctype('XHTML1_RDFA');
} else {
    echo $this->doctype('HTML5');
    $this->headMeta()->setCharset('UTF-8');
}
?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo Zend_Registry::get('Zend_Locale')->getLanguage(); ?>">
<head>
    <?php if(APPLICATION_ENV != ENV_PROD) : ?>
        <meta name="robots" content="noindex">
    <?php endif; ?>
<?php

/** @var  $active Ccsd_Website_Navigation_Page[] */
$site = Hal_Site::getCurrent();

if ($this->headTitle()->getContainer() == '') {
    $active = $this->nav()->findActive($this->nav()->getContainer());
    $this->headTitle($active ? $this->translate($active['page']->getLabel()) : $site->getShortname());
} elseif ($this->layout()->pageTitle != '') {
    $this->headTitle($this->layout()->pageTitle);
}

$this->headTitle()->prepend($site->getFullname());
$this->headTitle()->setSeparator(' - ');

$this->headLink(['rel'=>'dns-prefetch', 'href'=>CCSDLIB]);
$this->headLink(['rel'=>'dns-prefetch', 'href'=>'//cas.ccsd.cnrs.fr']);
$this->headLink(['rel'=>'dns-prefetch', 'href'=>'//cdn.mathjax.org']);
$this->headLink(['rel'=>'icon', 'type'=>'type/png', 'href'=>(file_exists(SPACE . 'public/favicon.png') ? SPACE_URL . 'favicon.png' : '/img/favicon.png')]);
$this->headLink(['rel'=>'search', 'type'=>'application/opensearchdescription+xml', 'href'=>'/search/opensearch', 'title'=>'HAL']);
$this->headLink()->appendStylesheet("/css/print_hal.css", 'print');

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
$this->headMeta()->appendHttpEquiv('Content-Language', Zend_Registry::get('Zend_Locale')->getLanguage());

$this->headScript()->appendScript("var lang = '" . Zend_Registry::get('Zend_Locale')->getLanguage() . "';");

echo $this->headTitle().PHP_EOL;
echo $this->headLink().PHP_EOL;
echo $this->headMeta().PHP_EOL;

// Ajouté le 28/07/2020:
$tag_name = '';
$page_active = $this->nav()->findActive($this->nav()->getContainer());
$tag_name = $page_active ? $this->translate($page_active['page']->getLabel()) : '';
$menu_label_origin = $page_active ? $page_active['page']->getLabel() : '';
if (!empty($menu_label_origin)) {
    $menu_label = trim($menu_label_origin);
}
//
$piwikId = Hal_Site::getCurrent()->getSetting('PIWIKID');
// Modification: intégration de Tarteaucitron et de différentes cookies.

$trackerRgpd = new \Hal\View\Tarteaucitron($this);
$trackerRgpd->addHeader();
//
$trackerMatomo = new \Hal\View\Matomo('//piwik-hal.ccsd.cnrs.fr/', $piwikId);
$trackerMatomo->addHeader();
//
$trackerAtinternet = new \Hal\View\Atinternet($this, $controller, $action, $tag_name, $documentid);
$trackerAtinternet->addHeader();
//
$trackerAddtoany = new \Hal\View\Addtoany($this);
$trackerAddtoany->addHeader();

// -------------------------------------------------

echo $this->headScript().PHP_EOL;

$this->jQuery()
    ->addJavascriptFile("/js/translations.php?lang=" . Zend_Registry::get('lang'))
    ->addJavascriptFile(CCSDLIB ."/v3/js/bootstrap.min.js")
    ->addJavascriptFile(CCSDLIB ."/js/form.js")
    ->addJavascriptFile("/js/utile.js")
    // CSS
    ->addStylesheet(CCSDLIB . '/css/custom-theme/jquery-ui-1.10.0.custom.css')
    ->addStylesheet(CCSDLIB . '/v3/css/bootstrap.min.css')
    ->addStylesheet(CCSDLIB . '/css/ccsd.css')
    ->addStylesheet('/css/hal.css');

if ('index' != $controller && 'page' != $controller) {
    $this->jQuery()
        ->addJavascriptFile(CCSDLIB . "/js/datepicker/datepicker-" . Zend_Registry::get('lang') . ".js")
        ->addJavascriptFile(CCSDLIB . "/js/datepicker.js");
}

//CSS spécifique au site
if ($this->cssFile) {
    $this->jQuery()->addStylesheet($this->cssFile);
}

echo $this->jQuery()->setLocalPath(CCSDLIB . '/js/jquery/jquery-1.12.4.min.js')->enable()->setUiLocalPath(CCSDLIB . '/js/jquery-ui-1.11.4/jquery-ui.min.js')->UiEnable();

?>

<script src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML" async></script>
<script type='text/x-mathjax-config'>MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['$$','$$']]}});</script>
<style type="text/css">
html {
	position: relative;
	min-height: 100%;
}
</style>
</head>
<body>$this->translate($page_active['page']->getLabel())
<?php $this->navbar(true, array('languages' =>  Zend_Registry::get('languages'), 'lang' => Zend_Registry::get('lang')), true, array('isLogged' => Hal_Auth::isLogged()), PREFIX_URL); ?>
<div id="container" class="container<?php echo $this->containerClass;?>">
    <div class="logo">
        <?php
        if (is_file(SPACE . LAYOUT . 'header.' . Zend_Registry::get('lang') . '.html')) {
            //Header prédéfini du portail
            echo file_get_contents(SPACE . LAYOUT . 'header.' . Zend_Registry::get('lang') . '.html');
        } else {
            //Header par défaut du module (portail, collection)
            $title = Zend_Registry::get('website')->getFullname() ;
            $name = '';
            if (MODULE == SPACE_PORTAIL)
                $name = PORTAIL;
            else 
                $name = COLLECTION;
            
            ?>
            <table width="100%" cellpadding="5" style="border:1px solid #ccc; margin-bottom:10px; padding:10px;">
                <tr>
                    <td><h1><?php echo $title . ' ' . $name; ?></h1></td>
                    <td align="right"><img src="/img/tampon-hal.jpg" /></td>
                </tr>
            </table>
            <?php } ?>
    </div>
    <div class="row<?php echo $this->containerClass;?>">
    <?php if ($this->navigation == Ccsd_Website_Style::MENU_LIST || $this->navigation == Ccsd_Website_Style::MENU_ACCORDION) {
        $class="col-md-2";
    } else {
        $class = "col-md-12";
    }?>
        <div class="<?php echo $class; ?>">
            <?php echo $this->sidebar($this->navigation, $this->nav(),PREFIX_URL); ?>
            <?php if ($this->navigation == Ccsd_Website_Style::MENU_LIST || $this->navigation == Ccsd_Website_Style::MENU_ACCORDION) {?>
        </div>
        <div class="col-md-10">
            <?php }?>
            <div class="corps">
                <?php if ($style->displayBreadCrumbs()) {
                    echo $breadcrumbs = trim($this->render('common/breadcrumbs.phtml'));
                    if ($breadcrumbs == '' && $this->layout()->pageTitle != '') {
                        ?>
                        <ol class="breadcrumb">
                            <li class="active"> <?php echo $this->layout()->pageTitle; ?> </li>
                            <?php if(!empty($this->layout()->docLink)) { ?>
                                <a href="<?php echo $this->layout()->docLink; ?>" target="_blank" rel="noopener"><span class="glyphicon glyphicon-question-sign" style="float:right; font-size:22px;" data-toggle="tooltip" data-original-title="Documentation"></span></a>
                            <?php }?>
                        </ol>
                    <?php }
                } else {
                    if ($this->layout()->pageTitle != '') {
                        $title = $this->layout()->pageTitle;
                    } else {
                        $active = $this->nav()->findActive($this->nav()->getContainer());
                        $title = $active ? $active['page']->getLabel() : '';
                    }

                    if (trim($title) != '') { ?>
                        <h1><?php echo $this->translate($title);?></h1>
                    <?php } ?>
                <?php } ?>
                <?php if ($this->layout()->pageDescription != '') { ?>
                    <blockquote><?php echo $this->layout()->pageDescription;?></blockquote>
                    <hr />
                <?php } ?>
                <div id="flash-messages">
                    <?php
                    echo $this->DisplayFlashMessages('danger', false);
                    echo $this->DisplayFlashMessages('warning', true);
                    echo $this->DisplayFlashMessages('success', true);
                    echo $this->DisplayFlashMessages('info', true);5326

                    ?>
                </div>
                <?php
                // Développement : affichage des mails
                if ( APPLICATION_ENV == ENV_DEV || APPLICATION_ENV == ENV_TEST || APPLICATION_ENV == ENV_PREPROD ) {
                    $session = new Zend_Session_Namespace();
                    if ( isset($session->mail) ) {
                        if (! is_array($session->mail)) {
                            $session->mail = array($session->mail);
                        }
                        foreach($session->mail as $mail) {
                            if ($mail instanceof Hal_Mail) {
                                $this->mail = $mail;
                                echo $this->render('common/mail.phtml');
                            }
                        }
                        unset($session->mail);
                    }
                }

                echo $this->layout()->content ;?>

            </div>
            <?php if ($this->displayErrors) {echo $this->render('common/errors.phtml');}?>
        </div>
    </div>
    <?php //if ( in_array(APPLICATION_ENV, [ENV_DEV, ENV_TEST]) ) { echo $this->render('common/debug.phtml'); } ?>  <!-- Ligne provisoirement desactivee le 06.08.2020. -->
</div>
<?php echo $this->render('common/footer.phtml'); ?>

<script type="text/javascript">
    $(document).ready(function () {
        $(document.body).tooltip({ selector: '[data-toggle="tooltip"]' , html: true, container: 'body'});
    });
</script>

<?php

// --------------------------------------

echo $trackerAtinternet->getHeader();

echo $trackerMatomo->getHeader();

echo $trackerAddtoany->getHeader();
// --------------------------------------
?>

</body>
</html>
