<?php
Zend_Controller_Front::getInstance()->getRequest()->setActionName($this->page);
if (isset($this->controller) && $this->controller != '') {
    Zend_Controller_Front::getInstance()->getRequest()->setControllerName($this->controller);
}

if ($this->mode == 'edit') {
    //Edition de la page
    ?>
    <style>
        .mce-fullscreen {
            z-index: 2000;
        }
    </style>

    <?php
    $this->jQuery()->addJavascriptFile(CCSDLIB ."/js/tinymce/jquery.tinymce.min.js")
        ->addJavascriptFile(CCSDLIB ."/js/tinymce/tinymce.min.js")
        ->addJavascriptFile("/js/page/en_GB.js")
        ->addJavascriptFile("/js/page/fr_FR.js")
        ->addJavascriptFile("/js/page/render.js")
        ->addJavascriptFile(CCSDLIB ."/js/tinymce_patch.js");

    echo $this->form;
    ?>
    <script>

        addWidgHalToTinyMCE(tinymce);

        __initMCE ('.textarea-group:last textarea', undefined, {
            theme: "modern",
            plugins: "link image code fullscreen table emoticons widghal",
            toolbar1: "bold italic underline | forecolor backcolor | styleselect | undo redo | alignleft aligncenter alignright alignjustify | table | bullist numlist | link image | widghal  | code | fullscreen",
            menubar: false,
            extended_valid_elements: "widget[style|data-mce-widget|data-mce-widget-in]",
            language  : '<?php echo Zend_Registry::get('lang') == 'fr' ? 'fr_FR' : 'en_GB';?>',
            convert_urls : false
        });

    </script>

<?php

} else {
    $this->jQuery()->addJavascriptFile('https://www.google.com/jsapi');
    $this->jQuery()->addJavascript('google.load("visualization", "1.0", {"packages":["corechart"]});');

    //Widget
    $pattern = '%<widget>([^<]+)</widget>%';
    $content = $this->content;
    preg_match_all($pattern, $content, $matches);
    if (isset($matches[1]) && is_array($matches[1])) {
        foreach ($matches[1] as $widget) {
            $content = str_replace('<widget>' . $widget . '</widget>', $this->widget($widget), $content);
        }
    }
    echo $content;

    if ($this->canEdit) {
        Zend_Controller_Front::getInstance()->getRequest()->setActionName($this->page);
        ?>
        <div class="form-actions text-center">
            <form action=""<?php echo PREFIX_URL . 'page/render/' . $this->page . '/edit'?> method="post" style="margin:0;">
                <input type="hidden" name="method" value="edit" />
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-pencil"></i>&nbsp;<?php echo $this->translate('Modifier le contenu de la page')?></button>
            </form>
        </div>
    <?php
    }
}



