Bonjour %%USER%%,


Ce message est une relance.

Nouveau dépôt à expertiser sur %%PORTAIL%% ( %%PORTAIL_URL%% ).

------------------------------------------------------------------------------
identifiant    : %%DOC_ID%%
url            : %%DOC_URL%% (vous devez vous connecter avant d'accéder à cet URL)
version        : %%DOC_VERSION%%
déposant       : %%DOC_CONTRIBUTOR%%
date de dépôt  : %%DOC_DATE%%
titre          : %%DOC_TITLE%%
auteur(s)      : %%DOC_AUTHORS%%
laboratoire(s) : %%DOC_LABOS%%
domaine(s)     : %%DOC_DOMAINS%%
------------------------------------------------------------------------------

Merci de votre expertise sur ce document.

-----------------
L'équipe %%PORTAIL%%
HAL CCSD
