Bonjour %%USER%%,

Merci pour votre expertise du document %%DOC_ID%% sur %%PORTAIL%% ( %%PORTAIL_URL%% ).

Ce dépôt a été remis en modération avec votre avis et les modérateurs ont été informés par courriel.

------------------------------------------------------------------------------
identifiant    : %%DOC_ID%%
url            : %%DOC_URL%% (vous devez vous connecter avant d'accéder à cet URL)
version        : %%DOC_VERSION%%
déposant       : %%DOC_CONTRIBUTOR%%
date de dépôt  : %%DOC_DATE%%
titre          : %%DOC_TITLE%%
auteur(s)      : %%DOC_AUTHORS%%
laboratoire(s) : %%DOC_LABOS%%
domaine(s)     : %%DOC_DOMAINS%%
------------------------------------------------------------------------------

Merci pour votre expertise,
sincères salutations,
--
L'équipe %%PORTAIL%%
HAL CCSD
