Bonjour %%USER%%,

Nouveau dépôt sur %%PORTAIL%% ( %%PORTAIL_URL%% ).

------------------------------------------------------------------------------
identifiant : %%DOC_ID%%
version : %%DOC_VERSION%%
déposant : %%DOC_CONTRIBUTOR%%
date de soumission : %%DOC_DATE%%
type de document : %%DOC_TYPDOC%%
titre : %%DOC_TITLE%%
auteur(s) : %%DOC_AUTHORS%%
laboratoire(s) : %%DOC_LABOS%%
domaine(s) : %%DOC_DOMAINS%%
------------------------------------------------------------------------------

Merci de vérifier ce document en vous connectant sur %%PORTAIL_URL%%

-----------------
L'équipe %%PORTAIL%%/CCSD
