Bonjour %%USER%%,

Merci de bien vouloir apporter les corrections suivantes à votre document %%DOC_ID%% (version %%DOC_VERSION%%) en vous connectant au serveur %%PORTAIL%% ( %%PORTAIL_URL%% )
%%MSG_MODERATEUR%%

Sans modification ou réponse de votre part dans les 5 mois (vous pouvez utiliser la fonctionnalité "Annoter/Répondre à la demande de modification"), ce document sera supprimé du serveur.

Cordialement,

-----------------
L'équipe %%PORTAIL%%/CCSD