Bonjour %%USER%%,

%%REQUEST_USER%% (%%REQUEST_USER_EMAIL%%) souhaite consulter le fichier sous embargo (%%DOC_FILENAME%%) associé à votre document %%DOC_ID%%, version %%DOC_VERSION%%.

Pour répondre à cette demande, vous êtes invité à :

1- Vous rendre sur %%PORTAIL%% ( %%PORTAIL_URL%% ) à l'espace "Mon espace > Mes partages de fichiers sous embargo"
ou
2- Répondre en cliquant directement sur un des liens suivant :
    * <a href='%%REQUEST_URL%%/user/filerequest/docid/%%DOCID%%/uid/%%REQUEST_UID%%/accept/1'>Accepter</a> l'accès au fichier ;
    * <a href='%%REQUEST_URL%%/user/filerequest/docid/%%DOCID%%/uid/%%REQUEST_UID%%/accept/0'>Refuser</a> l'accès au fichier.


Cordialement,

-----------------
L'équipe %%PORTAIL%%
HAL CCSD