<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate("Oups...!"); ?></h4>
      </div>
      <div class="modal-body">
      
      
      
      <p>
            <?php 
                if (!is_array ($this->msg)) {
                    $this->msg = array($this->msg);
                }
                
                foreach ($this->msg as $k => $v) {
                    echo $this->translate ($v);
                }
            ?>
            
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate("Fermer"); ?></button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->