
<?php $this->jQuery()->addStylesheet(CCSDLIB ."/css/ui-lightness/jquery-ui-1.10.3.custom.min.css");?>
<style>
	.ui-autocomplete {
		max-height: 100px;
		overflow-y: auto;
		/* prevent horizontal scrollbar */
		overflow-x: hidden;
		background: #ffffff;
	}
	.ui-helper-hidden-accessible {
		display:none;
	}
	/* IE 6 doesn't support max-height
	 * we use height instead, but this forces the menu to always be this tall
	 */
	* html .ui-autocomplete {
		height: 100px;
	}
	.ui-menu .ui-menu-item a.ui-state-focus {
		color: #ffffff;
		border:0;
		border-radius: 0;
		text-decoration: none;
		background-color: #0081c2;
		background-image: -moz-linear-gradient(top, #0088cc, #0077b3);
		background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#0088cc), to(#0077b3));
		background-image: -webkit-linear-gradient(top, #0088cc, #0077b3);
		background-image: -o-linear-gradient(top, #0088cc, #0077b3);
		background-image: linear-gradient(to bottom, #0088cc, #0077b3);
		background-repeat: repeat-x;
		outline: 0;
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff0088cc', endColorstr='#ff0077b3', GradientType=0);
	}
	.ui-widget {
		font-family: inherit;		
	}
</style>

<h3><?php echo $this->translate("Métadonnées")?></h3>
<?php echo $this->form;?>


<?php 
//$session = new Zend_Session_Namespace(SESSION_NAMESPACE);
//Zend_Debug::dump($session->document->toArray());
?>

<script type="text/javascript">
<!--
$(function () {
	//Element de type référentiel
	$('.referentiel').each(function(){
		//Récupération des infos sur l'entrée du référentiel
		if ($(this).val() != '' && $(this).val() != '0' && ! isNaN($(this).val())) {
			getRefInfos($(this).attr('data-ref'), $(this).val(), $(this));
		}
		//Autocompletion		
		$(this).autocomplete({
			source: '/submit/ref/type/' + $(this).attr('data-ref'),
			minLength: 2,
			select: function( event, ui ) {
				//Récupération des données du journal
				getRefInfos($(this).attr('data-ref'), ui.item.id, $(this));					
			}
		});
	});	
});

/**
 * Récupération des informations sur une entrée d'un référentiel
 * @param string ref : type du référentiel (journal, anr, ...)
 * @param int id : identifiant de l'entrée du référentiel
 * @param objet elem : champ d'autocompletion
 */
function getRefInfos(ref, id, el) 
{
	$.ajax({
		url: '/submit/ref',
		method: 'post',
		data: {type: ref, id: id},
	}).done(function(data) {
		el.val($('.' + ref + '-name', data).text());
		//if (el.parent().find('.' + ref)) {
		//	el.parent().find('.' + ref).replaceWith(data);
		//} else {
			el.closest('dd').append(data);

		//}
	});
}

//-->
</script>