<?php 
$this->jQuery()
    ->addStylesheet("/css/bootstrap-wysihtml5.css")
    ->addJavascriptFile("/js/wysihtml5-0.js")
    ->addJavascriptFile("/js/bootstrap-wysihtml5.js");
?>     
<textarea class="textarea" placeholder="Enter text ..." style="width: 100%; height: 500px;">
<?php echo $this->content;?>
</textarea>

<div class="form-actions">
    <div class="pull-right">
        <button type="submit" class="btn btn-primary">Enregistrer</button>
        <button type="button" class="btn">Annuler</button>
    </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
	  $('.textarea').wysihtml5();
  });
</script>