<?php
$form = $this->page->getForm ( $this->i );

$form->removeDecorator ( 'Form' );

echo $form;

if (! $this->page->isMultiple ()) {
	// Page simple
	?>
<script>
	$('#type option[type="<?php echo get_class($this->page)?>"]').attr('disabled', 'disabled');
	</script>
<?php
}
if ($this->page->isFile ()) {
	// Pour contourner le pb de Zend_File
	?>
<script>
        $(document).ready(function(){
            //alert($('#page_<?php echo $this->i?> input:file').length);
            $('#page_<?php echo $this->i?> input:file').each(function() {
            // alert('page_<?php echo $this->i?>[' + $(this).attr('name') + ']');
            $(this).attr('name', 'pages_<?php echo $this->i?>[' + $(this).attr('name') + ']');
            });
        });
	</script>
<?php
}




if ($this->page->getPageClass () == 'Hal_Website_Navigation_Page_Structure' || $this->page->getPageClass () == 'Hal_Website_Navigation_Page_Author') {
	?>
<script>
        $(document).ready(function(){
<?php
if (is_array($this->page->getFilter ())) {
	foreach ( $this->page->getFilter () as $structid ) {
		$struct = new Hal_Document_Structure ( $structid );
		$type = '';
		if ($struct->getTypestruct()!='') {
			$type = ' <small>[' . $this->translate ( $struct->getTypestruct() ) . ']</small>';
		}
?>
            addAffi('#pages_<?php echo $this->i; ?>-filter', "<?php echo $this->escape($struct->getStructName()) . $type ?>", "<?php echo $structid?>");
<?php
   }
}
?>
            $('#pages_<?php echo $this->i; ?>-filter').val('');
        });
    </script>
<?php
}




/* ---- JS Collections ------*/
if ($this->page->getPageClass () == 'Hal_Website_Navigation_Page_Collections')  : ?>
<script>
	$(document).ready(function(){
<?php if (is_array($this->page->getFilter ()))  : ?>
	<?php foreach ( $this->page->getFilter () as $collCode ) : ?>
	<?php $coll = Hal_Site::exist($collCode, Hal_Site::TYPE_COLLECTION, true); ?>
		addCollection('#pages_<?php echo $this->i; ?>-filter', "<?php echo $this->escape($coll->getName()) ?>", "<?php echo $coll->getSid() ?>", "<?php echo $coll->getCode() ?>");
	<?php endforeach; ?>
<?php endif; ?>
            $('#pages_<?php echo $this->i; ?>-filter').val('');
        });
    </script>
<?php endif; ?>