Bonjour %%USER%%,

Vous venez de créer un compte sur le portail HAL ( %%PORTAIL%%  %%PORTAIL_URL%% )

Pour activer votre nouveau compte et pouvoir vous authentifier au système, merci de bien vouloir cliquer sur le lien

<a href='%%TOKEN_VALIDATION_LINK%%'>%%TOKEN_VALIDATION_LINK%%</a>

Si le lien ne fonctionne pas depuis votre logiciel de messagerie, nous vous invitons à le copier-coller dans la barre d'adresse de votre navigateur.


Cordialement,

--
L'équipe du portail %%PORTAIL%%
HAL CCSD


