Bonjour %%USER%%,

Un compte viens d'etre cree sur le portail ( %%PORTAIL%%  %%PORTAIL_URL%% )

Pour activer votre nouveau compte et pouvoir initialiser votre mot de passe, merci de bien vouloir cliquer sur le lien

<a href='%%TOKEN_VALIDATION_LINK%%'>%%TOKEN_VALIDATION_LINK%%</a>

Si le lien ne fonctionne pas depuis votre logiciel de messagerie, nous vous invitons à le copier-coller dans la barre d'adresse de votre navigateur.

Cordialement,

--
L'équipe du portail %%PORTAIL%%

