Bonjour %%USER%%,

Fin de l'expertise du document %%DOC_ID%% sur le portail HAL ( %%PORTAIL%%  %%PORTAIL_URL%% ).

Ce dépôt n'est plus à expertiser.

------------------------------------------------------------------------------
identifiant    : %%DOC_ID%%
url            : %%DOC_URL%% (vous devez vous connecter avant d'accéder à cet URL)
version        : %%DOC_VERSION%%
déposant       : %%DOC_CONTRIBUTOR%%
date de dépôt  : %%DOC_DATE%%
titre          : %%DOC_TITLE%%
auteur(s)      : %%DOC_AUTHORS%%
laboratoire(s) : %%DOC_LABOS%%
domaine(s)     : %%DOC_DOMAINS%%
------------------------------------------------------------------------------


sincères salutations,
--
L'équipe du portail %%PORTAIL%%
HAL CCSD
