Bonjour %%USER%%,

Nouveau dépôt sur le portail %%PORTAIL%% de HAL ( %%PORTAIL_URL%% ).
<a href="%%PORTAIL_URL%%/moderate/documents/docid/%%DOCID%%">%%PORTAIL_URL%%/moderate/documents/docid/%%DOCID%%</a>

------------------------------------------------------------------------------
identifiant : %%DOC_ID%%
version : %%DOC_VERSION%%
déposant : %%DOC_CONTRIBUTOR%%
date de soumission : %%DOC_DATE%%
type de document : %%DOC_TYPDOC%%
titre : %%DOC_TITLE%%
auteur(s) : %%DOC_AUTHORS%%
laboratoire(s) : %%DOC_LABOS%%
domaine(s) : %%DOC_DOMAINS%%
------------------------------------------------------------------------------

Merci de vérifier ce document.

-----------------
L'équipe du portail %%PORTAIL%%
HAL CCSD
