Bonjour %%USER%%,

Ce message automatique vous indique les nouveaux documents correspondant à votre alerte : %%ALERT_NAME%%
La fréquence de votre alerte est : %%ALERT_FREQ%%
Il y a %%ALERT_NUM_DOCS%% documents correspondant à votre critère d'abonnement.
Voici le lien pour accéder à votre recherche dans le portail HAL : <a href="%%ALERT_SEARCH_URL%%">%%ALERT_SEARCH_URL%%</a>
Vous pouvez modifier vos alertes en ligne à partir de Mon espace/Mes recherches

%%ALERT_DOC_LIMIT%%
------------------------------------------------------------------------------
%%ALERT_DOC_LIST%%
------------------------------------------------------------------------------

--
L'équipe du portail %%PORTAIL%%
HAL CCSD
