%%MAIL_TO_FULLNAME%%,

Un nouveau document a été mis en ligne sur le portail dont vous êtes administrateur :

<a href='%%DOCUMENT_URL%%' style="color:#292063;">%%DOC_REF%%</a>


Sincères salutations,
--
Message automatique du %%MAIL_SIGNATURE%%

P.S. : Le document peut être inaccessible car celui-ci doit être indexé par nos machines.

<a href='%%MODIFY_PROFIL_URL%%'>Je ne souhaite plus recevoir ce type de mail.</a>