Bonjour %%USER%%,

Une demande de partage de propriété a été faite pour votre document %%DOC_ID%% ( <a href='%%DOC_URL%%'>%%DOC_URL%%</a> ).

    titre     : %%DOC_TITLE%%
    auteur(s) : %%DOC_AUTHORS%%

Voici la demande de %%REQUEST_USER%% (%%REQUEST_USER_EMAIL%%) :
%%REQUEST_MESSAGE%%
    
Pour répondre à cette demande, vous devez aller sur %%PORTAIL%% ( %%PORTAIL_URL%%/user/docowner ) dans la page "Mon espace > Mes partages de propriétés"

Cordialement,

-----------------
L'équipe du portail %%PORTAIL%%
HAL CCSD