%%MAIL_TO_FULLNAME%%,

Un nouveau document est en ligne sur HAL :
<a href='%%DOCUMENT_URL%%' style="color:#292063;">%%DOC_REF%%</a>


L'un des auteurs est affilié à la structure %%STRUCTNAME%% dont vous êtes référent.

En tant que référent, vous avez les droits de propriété sur ce document : vous pouvez compléter les métadonnées, ajouter un fichier ou une nouvelle version.


Sincères salutations,
--
Message automatique du %%MAIL_SIGNATURE%%

P.S. : Le document peut être inaccessible car celui-ci doit être indexé par nos machines.

<a href='%%MODIFY_PROFIL_URL%%'>Je ne souhaite plus recevoir ce type de mail.</a>