Bonjour %%USER%%,

    Les informations concernant votre nouveau dépôt sur le portail de HAL (%%PORTAIL%% <a href="%%DOC_URL%%">%%DOC_URL%%</a> ) sont :

%%DOC_REF%%
------------------------------------------------------------------------------
identifiant : %%DOC_ID%%
version : %%DOC_VERSION%%
mot de passe : %%DOC_PWD%%
date de soumission : %%DOC_DATE%%
------------------------------------------------------------------------------

Ces informations vous seront nécessaires lors de vos éventuelles modifications sur cet article.

Cordialement,

-----------------
L'équipe du portail %%PORTAIL%%
HAL CCSD

P.S. : Le document peut être inaccessible car celui-ci doit être indexé par nos machines.







