Bonjour %%USER%%,

Malheureusement, votre document (%%DOC_ID%%, version %%DOC_VERSION%%) ne peut pas être accepté sur le portail HAL ( %%PORTAIL%%  %%PORTAIL_URL%% ).

    titre     : %%DOC_TITLE%%
    auteur(s) : %%DOC_AUTHORS%%

%%MSG_MODERATEUR%%

Si vous désirez des informations complémentaires concernant la validation scientifique de ce dépôt, veuillez écrire à hal.support@ccsd.cnrs.fr

Cordialement,

-----------------
L'équipe du portail %%PORTAIL%%
HAL CCSD