Bonjour %%USER%%,

Votre document %%DOC_ID%%, version %%DOC_VERSION%% est maintenant en ligne sur le portail HAL ( %%PORTAIL%% %%PORTAIL_URL%% ).

Le lien pour visualiser votre article est : <a href="%%DOC_URL%%">%%DOC_URL%%</a>

Ce dépôt a été transféré sur arXiv et son identifiant arXiv définitif sera automatiquement ajouté à HAL dès que celui-ci sera validé par arXiv.

%%MSG_MODERATEUR%%

Cordialement,

-----------------
L'équipe du portail %%PORTAIL%%
HAL CCSD