Bonjour %%USER%%,

Votre demande d'accès au fichier sous embargo (%%DOC_FILENAME%%) pour le document %%DOC_ID%% ( <a href='%%DOC_URL%%'>%%DOC_URL%%</a> ) a été accepté par %%ACCEPTEDBY%%
Le fichier vous est maintenant accessible en consultant <a href='%%DOC_URL%%'>%%DOC_URL%%</a> en étant connecté ou directement via cette URL : <a href='%%DOC_FILE_URL%%'>%%DOC_FILE_URL%%</a>
Ce fichier est placé sous embargo. Il ne peut être utilisé qu'à usage personnel et ne doit pas être divulgué.

Cordialement,

-----------------
L'équipe du portail %%PORTAIL%%
HAL CCSD