Bonjour %%USER%%,

Les informations concernant votre nouvelle notice sur le portail de HAL (%%PORTAIL%%  %%PORTAIL_URL%% ) sont :

%%DOC_REF%%
------------------------------------------------------------------------------
identifiant : %%DOC_ID%%
version : %%DOC_VERSION%%
mot de passe : %%DOC_PWD%%
date de soumission : %%DOC_DATE%%
------------------------------------------------------------------------------

Ces informations vous seront nécessaires lors de vos éventuelles modifications sur ce dépôt.

Cordialement,

-----------------
L'équipe du portail %%PORTAIL%%
HAL CCSD