<style>
    #active {color:#428bca;}
</style>
<?php

$orderurl = '';
foreach($_GET as $key => $value){
    if (isset($_GET[$key]) && $key != 'order'){
        $orderurl .= '&'.$key.'='.$value;
    }
}

$this->layout()->pageDescription = $this->translate("Merci de bien vouloir vérifier, valider, modérer les articles suivants");

if (count($this->documents)) {
?>
    <h5 xmlns="http://www.w3.org/1999/html"><?php echo $this->translate('Nombre de documents à vérifier'); ?> : <span class="label label-primary"><?php echo $this->documents->getTotalItemCount();?></span></h5>
    <h5><?php echo $this->translate('Nombre de documents par page'); ?> : <span class="label label-primary"><?php echo $this->documents->getItemCountPerPage();?></span></h5>

    <div class="btn-group" style="margin-bottom: 5px;">
        <button type="button" id="filtre" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-filter"></span> <?php echo $this->translate('Filtres'); ?>  <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href="<?php echo '?filtre=askmodif' ?>" class="btn btn-xs<?php echo (isset($_GET['filtre']) && $_GET['filtre'] == 'askmodif') ? ' btn-primary active disabled' : ""?>">
                    <?php
                    echo $this->translate('Retour de modification');
                    ?>
                </a>
            </li>
            <li>
                <a href="<?php echo '?filtre=arxiv' ?>" class="btn btn-xs<?php echo (isset($_GET['filtre']) && $_GET['filtre'] == 'arxiv') ? ' btn-primary active disabled' : ""?>">
                    <?php
                    echo $this->translate('Arxiv');
                    ?>
                </a>
            </li>
            <li>
                <a href="<?php echo '?querypor=medihal' ?>" class="btn btn-xs<?php echo (isset($_GET['querypor']) && $_GET['querypor'] == 'medihal') ? ' btn-primary active disabled' : ""?>">
                    <?php
                    echo $this->translate('Medihal');
                    ?>
                </a>
            </li>
        </ul>

    <?php
    if (isset($_GET['filtre']) || isset($_GET['queryid']) || isset($_GET['queryuid']) || isset($_GET['querytype']) || isset($_GET['querytype']) || isset($_GET['querydate']) || isset($_GET['querynbdoc']) || isset($_GET['querypor'])) { ?>
        <button type="button" id="removefilter" onclick="link('/moderate/documents');" class="btn btn-default btn-sm" title="Supprime les filtres">
            <i class="glyphicon glyphicon-remove"></i>
        </button>
    <?php }?>
    </div>

    <?php
    if ($this->documents) {
        echo $this->paginationControl ( $this->documents, 'Sliding', 'partials/pagination.phtml', array (
        ));
    }
    if ($this->documents->getTotalItemCount() > $this->documents->getItemCountPerPage()){
    ?>
    <?php }?>

    <form action="/moderate/documents" method="post" id="list-documents">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="moderate" width="100%">
            <thead>
                <tr>
                    <th class="middle" style="width:16px"></th>
                    <th class="middle">
                        <div class="input-group">
                            <input type="text" id="type" value="<?php if (isset($_GET['querytype'])) {echo $_GET['querytype'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche par type de document");?>">
                        </div>
                    </th>
                    <th class="middle">
                        <div class="input-group">
                            <input type="text" id="id" value="<?php if (isset($_GET['queryid'])) {echo $_GET['queryid'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche par identifiant");?>">
                        </div>
                    </th>
                    <th class="middle">
                        <div class="input-group">
                            <input type="text" id="uid" value="<?php if (isset($_GET['queryuid'])) {echo $_GET['queryuid'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche par contributeur");?>">
                        </div>
                    </th>

                    <th class="middle">
                        <div class="input-group">
                            <input type="text" id="nbdoc" value="<?php if (isset($_GET['querynbdoc'])) {echo $_GET['querynbdoc'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche selon <br>le nombre de dépôts");?>">
                        </div>
                    </th>
                    <th class="middle">
                        <div class="input-group">
                            <input type="text" id="date" value="<?php if (isset($_GET['querydate'])) {echo $_GET['querydate'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche par date");?>">
                        </div>
                    </th>
                    <th class="middle">
                        <div class="input-group">
                            <input type="text" id="por" value="<?php if (isset($_GET['querypor'])) {echo $_GET['querypor'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche par portail");?>">
                        </div>
                    </th>
                </tr>
                <tr>
                    <th class="middle" style="width:16px"><input type="checkbox" class="select-checkbox"/></th>
                    <th class="middle">
                        <div style="display:flex;">
                            <span style="margin-right:4px;"><?php echo $this->translate('Type de document'); ?></span>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=typeasc"; echo $orderurl;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="typeasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=typedesc"; echo $orderurl;?>" style="align-self: center; margin-left:2px;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="typedesc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                        </div>
                    </th>
                    <th class="middle">
                        <div style="display:flex;">
                            <span style="margin-right:4px;"><?php echo $this->translate('Document'); ?></span>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=docasc"; echo $orderurl;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="docasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=docdesc"; echo $orderurl;?>" style="align-self: center; margin-left:2px;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="docdesc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                        </div>
                    </th>
                    <th class="middle">
                        <div style="display:flex;">
                            <span style="margin-right:4px;"><?php echo $this->translate('Contributeur'); ?></span>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=contasc"; echo $orderurl;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="contasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=contdesc"; echo $orderurl;?>" style="align-self: center; margin-left:2px;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="contdesc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                        </div>
                    </th>
                    <th class="middle">
                        <div style="display:flex;">
                            <span style="margin-right:4px;"><?php echo $this->translate('Nombre de dépôts'); ?></span>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=nbasc"; echo $orderurl;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="nbasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=nbdesc"; echo $orderurl;?>" style="align-self: center; margin-left:2px;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="nbdesc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                        </div>
                    </th>
                    <th class="middle">
                        <div style="display:flex;">
                            <span style="margin-right:4px;"><?php echo $this->translate('Déposé le'); ?></span>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=dateasc"; echo $orderurl;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="dateasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=datedesc"; echo $orderurl;?>" style="align-self: center; margin-left:2px;" id="<?php if (!isset ($_GET['order']) || (isset ($_GET['order']) && $_GET['order']=="datedesc")) { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                        </div>
                    </th>
                    <th class="middle">
                        <div style="display:flex;">
                            <span style="margin-right:4px;"><?php echo $this->translate('Portail'); ?></span>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=porasc"; if (isset($_GET['page'])) : echo '&page='.$_GET['page'];endif; if (isset($_GET['rows'])) : echo '&rows='.$_GET['rows'];endif;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="porasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                            <a href="<?php echo PREFIX_URL."moderate/documents?order=pordesc"; if (isset($_GET['page'])) : echo '&page='.$_GET['page'];endif; if (isset($_GET['rows'])) : echo '&rows='.$_GET['rows'];endif;?>" style="align-self: center; margin-left:2px;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="pordesc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php

                $docidsInProgress = is_array($this->inProgress) ? array_keys($this->inProgress) : array();

                foreach($this->documents as $data) {
                    $document = Hal_Document::find($data['DOCID']);

                    ?>
                    <tr <?php echo (in_array($data['DOCID'], $docidsInProgress) ? 'class="warning"' : '') ?>>
                        <td class="middle"><input type="checkbox" name="docid[]" value="<?php echo $data['DOCID']; ?>" class="checkbox-docid" /></td>
                        <td class="middle">
                            <span style="white-space: normal; display:inline-block" class="<?php echo Hal_Settings::getLabelClassName($document->getTypDoc()); ?>">
                                <?php echo $this->translate('typdoc_' . $document->getTypDoc()); ?>
                            </span>
                        </td>
                        <td class="middle">
                            <a href="javascript:void(0);" onclick="selectDocument(<?php echo $data['DOCID']; ?>)">
                                <?php if ($document->getFormat() == Hal_Document::FORMAT_FILE) { ?>
                                    <i class="glyphicon glyphicon-file"></i>
                                <?php } ?>
                                <?php echo strip_tags($document->getCitation('full')); ?>
                            </a>
                            <a href=<?php echo PREFIX_URL?>moderate/documents/docid/<?php echo $data['DOCID'];?> target="_blank" data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Ouvrir dans un nouvel onglet')?>"><i class="glyphicon glyphicon-asterisk"></i></a>
                            <?php if (Hal_Document_Logger::hasAction($document->getDocid(), Hal_Document_Logger::ACTION_ASKMODIF)) { ?>
                                <span class="label label-info"> Retour de modification </span>
                            <?php } ?>
                            <?php if ($document->getStatus() == Hal_Document::STATUS_TRANSARXIV) { ?>
                                <span class="arxiv" style="float:right;"> arXiv.org </span>
                            <?php } ?>
                            <?php if (in_array($data['DOCID'], $docidsInProgress)) { ?>
                                <span class="label label-warning"><i class="glyphicon glyphicon-exclamation-sign"></i>&nbsp;<?php echo $this->translate('En cours de modération par ') . ' ' . $this->inProgress[$data['DOCID']]; ?></span>
                            <?php } ?>
                        </td>
                        <td class="middle"><?php echo $data['SCREEN_NAME'] ?></td>
                        <td class="middle text-center">
                            <span class="label label-primary"><?php echo $data['NBDOCVIS']; ?></span>
                            <?php if ($data['NBDOCSCI'] > 0){?>
                                <span class="label label-warning"><?php echo $data['NBDOCSCI']; ?></span>
                            <?php }?>
                            <?php if ($data['NBDOCREF'] > 0){?>
                            <span class="label label-danger"><?php echo $data['NBDOCREF']; ?></span>
                            <?php }?>
                        </td>
                        <td class="middle"><?php echo $data['DATESUBMIT'] ?></td>
                        <td class="middle"><?php echo $data['SITE'] ?></td>
                    </tr>
                <?php } ?>
            </tbody>
            <tfoot>
                <tr>
                    <th><input type="checkbox" class="select-checkbox" /></th>
                    <th colspan="6"><button type="submit" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-eye-open"></i>&nbsp;<?php echo $this->translate('Voir'); ?></button> </th>
                </tr>
            </tfoot>
        </table>
    </form>
    <div class="btn-group">
    <?php
    if ($this->documents) {
    echo $this->paginationControl ( $this->documents, 'Sliding', 'partials/pagination.phtml', array (
    ));
    }?>
    </div>
    <script language="JavaScript">
        $('.select-checkbox').click(function() {
            $('#moderate .checkbox-docid, .select-checkbox').prop('checked', $(this).is(':checked'));
        });

        /**
         * Selection d'un document
         * @param docid
         */
        function selectDocument(docid)
        {
            $('#moderate .checkbox-docid, .select-checkbox').prop('checked', false);
            $('#moderate .checkbox-docid[value="' + docid + '"]').prop('checked', true);
            $('#list-documents').submit();
        }

        $('input').on("focus", function() {
            $(this).keyup(function (e) {
                if (e.keyCode == 13 && $(this).val() != '') {
                    window.location.replace("<?php echo PREFIX_URL."moderate/documents?query"?>" + $(this).attr("id") + "=" + $(this).val());
                } else if (e.keyCode == 13){
                    window.location.replace("<?php echo PREFIX_URL."moderate/documents"?>");
                }
            });
        });
    </script>

<?php } else { ?>
    <div class="alert alert-success"><strong><?php echo $this->translate("Aucun dépôt ne correspond à la recherche :)");?></strong></div>
<?php } ?>