<style>
    #active {color:#428bca;}
</style>
<?php
/**
 * Created by PhpStorm.
 * User: baptiste
 * Date: 01/12/2015
 * Time: 11:47
 */

$orderurl = '';
foreach($_GET as $key => $value){
    if (isset($_GET[$key]) && $key != 'order'){
        $orderurl .= '&'.$key.'='.$value;
    }
}

$this->layout()->pageDescription = $this->translate("Liste des documents sous embargo");

if (count($this->documents)) {
    ?>

    <h5><?php echo $this->translate('Nombre de documents sous embargo'); ?> : <span class="label label-primary"><?php echo $this->documents->getTotalItemCount();?></span></h5>
    <h5><?php echo $this->translate('Nombre de documents par page'); ?> : <span class="label label-primary"><?php echo $this->documents->getItemCountPerPage();?></span></h5>

    <div class="btn-group">
    <?php
    if ($this->documents) {
        echo $this->paginationControl ( $this->documents, 'Sliding', 'partials/pagination.phtml', array (
        ));
    }
    if ($this->documents->getTotalItemCount() > $this->documents->getItemCountPerPage()){
    ?>
    <?php }?>
    </div>
    <form action="/moderate/embargo" method="post" id="list-documents">
        <table style="padding:0;border-spacing:0;border:0;width:100%" class="table table-striped table-bordered" id="moderate">
            <thead>
            <tr>
                <th class="middle">
                    <div class="input-group">
                        <input type="text" id="id" value="<?php if (isset($_GET['queryid'])) {echo $_GET['queryid'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche par identifiant");?>">
                    </div>
                </th>
                <th class="middle">
                </th>
                <th class="middle">
                    <div class="input-group">
                        <input type="text" id="uid" value="<?php if (isset($_GET['queryuid'])) {echo $_GET['queryuid'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche par contributeur");?>">
                    </div>
                </th>
                <th class="middle">
                    <div class="input-group">
                        <input type="text" id="date" value="<?php if (isset($_GET['querydate'])) {echo $_GET['querydate'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche par date");?>">
                    </div>
                </th>
                <th class="middle">
                    <div class="input-group">
                        <input type="text" id="por" value="<?php if (isset($_GET['querypor'])) {echo $_GET['querypor'];}?>" class="form-control" style="border-radius: 3px;" data-toggle="tooltip" title="<?php echo $this->translate("Recherche par portail");?>">
                    </div>
                </th>
            </tr>
            <tr>
                <th class="middle">
                    <div style="display:flex;">
                        <span style="margin-right:4px;"><?php echo $this->translate('Document'); ?></span>
                        <a href="<?php echo PREFIX_URL."moderate/documents?order=docasc"; echo $orderurl;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="docasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                        <a href="<?php echo PREFIX_URL."moderate/documents?order=docdesc"; echo $orderurl;?>" style="align-self: center; margin-left:2px;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="docdesc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                    </div>
                </th>
                <th class="middle">
                </th>
                <th class="middle">
                    <div style="display:flex;">
                        <span style="margin-right:4px;"><?php echo $this->translate('Contributeur'); ?></span>
                        <a href="<?php echo PREFIX_URL."moderate/documents?order=contasc"; echo $orderurl;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="contasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                        <a href="<?php echo PREFIX_URL."moderate/documents?order=contdesc"; echo $orderurl;?>" style="align-self: center; margin-left:2px;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="contdesc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                    </div>
                </th>
                <th class="middle">
                    <div style="display:flex;">
                        <span style="margin-right:4px;"><?php echo $this->translate('Déposé le'); ?></span>
                        <a href="<?php echo PREFIX_URL."moderate/documents?order=dateasc"; echo $orderurl;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="dateasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                        <a href="<?php echo PREFIX_URL."moderate/documents?order=datedesc"; echo $orderurl;?>" style="align-self: center; margin-left:2px;" id="<?php if (!isset ($_GET['order']) || (isset ($_GET['order']) && $_GET['order']=="datedesc")) { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                    </div>
                </th>
                <th class="middle">
                    <div style="display:flex;">
                        <span style="margin-right:4px;"><?php echo $this->translate('Portail'); ?></span>
                        <a href="<?php echo PREFIX_URL."moderate/documents?order=porasc"; if (isset($_GET['page'])) : echo '&page='.$_GET['page'];endif; if (isset($_GET['rows'])) : echo '&rows='.$_GET['rows'];endif;?>" style="align-self: center; margin-left:auto;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="porasc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri croissant");?>"><i class="glyphicon glyphicon-chevron-down"></i></a>
                        <a href="<?php echo PREFIX_URL."moderate/documents?order=pordesc"; if (isset($_GET['page'])) : echo '&page='.$_GET['page'];endif; if (isset($_GET['rows'])) : echo '&rows='.$_GET['rows'];endif;?>" style="align-self: center; margin-left:2px;" id="<?php if (isset ($_GET['order']) && $_GET['order']=="pordesc") { echo "active";}?>" data-toggle="tooltip" title="<?php echo $this->translate("Tri décroissant");?>"><i class="glyphicon glyphicon-chevron-up"></i></a>
                    </div>
                </th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($this->documents as $data) {
                $document = Hal_Document::find($data['DOCID']);
                ?>
                <tr class="docs">
                    <td class="middle"><?php echo $document->getCitation('full'); ?>
                        <input type="hidden" name="docid[]" class="docids" value="<?php echo $data['DOCID']?>">
                        <?php
                        $files = $document->getFiles();
                        if (count($files)) {
                            $j = 0;
                            $this->showType = true;
                            $this->readEmbargo = true;
                            foreach($files as $idf => $file) {
                                $this->file = $file;
                                $this->href = (isset($this->filesInTmpDir) && $this->filesInTmpDir) ? '/file/tmp/fid/' . $idf : '/file/index/docid/' . $document->getDocid() . '/filename/' . rawurlencode($file->getName());
                                echo $this->partial('partials/file-embargo.phtml', array(
                                    'file' => $this->file,
                                    'data' => $data,
                                    'href' => $this->href,
                                    'document' => $document,
                                    'readEmbargo' => $this->readEmbargo,
                                    'showType' => $this->showType
                                ));
                                $j++;
                            }
                        }
                        ?>
                    </td>
                    <td class="middle" style="text-align:center"><a href="javascript:void(0);" class="file-action" onclick="getListFiles($(this))" data-toggle="tooltip" title="" data-original-title="<?php echo $this->translate("Consulter les fichiers associés à ce document");?>"><i class="glyphicon glyphicon-list-alt"></i></a></td>
                    <td class="middle"><?php echo $data['SCREEN_NAME'] ?></td>
                    <td class="middle"><?php echo $data['DATESUBMIT'] ?></td>
                    <td class="middle"><?php echo $data['SITE'] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </form>
    <div class="btn-group">
    <?php
    if ($this->documents) {
        echo $this->paginationControl ( $this->documents, 'Sliding', 'partials/pagination.phtml', array (
        ));
    }
    ?>
    </div>
    <script>
        function getListFiles(elem)
        {
            var docid = $(elem).closest('.docs').find('.docids').val();
            $('.file' + docid).each(function (){
                if ($(this).is(':visible')) {
                    $(this).hide();
                } else {
                    $(this).css('display','block');
                }
            });
        }
        function getFileCalendar(id, uid, docid, datelimit, datevisible)
        {
            var callback = function( data ) {popoverFile("<?php echo $this->translate("Changer l'embargo du fichier");?>", data, id); };
            ajaxrequest('/moderate/ajaxgetfilecalendar', {id:id, uid:uid, docid:docid, datelimit:datelimit, datevisible:datevisible}, callback);
        }
        function popoverFile(title, data, id)
        {
            popover('#emb_' + id, title, data);
        }
        function popover(selector, title, content)
        {
            $(selector).popover('destroy');

            title += "<span style=\"float:right\">";
            title += "  <a href=\"javascript:void(0);\" onclick=\"$('" + selector + "').popover('destroy')\">";
            title += "    <i class=\"glyphicon glyphicon-remove\"></i>";
            title += "  </a>";
            title += "</span>";

            $(selector).popover({
                content: content,
                title: title,
                placement: 'bottom',
                container: 'body',
                html: true
            }).popover('show');

        }
        function ajaxrequest(url, data, callback)
        {
            $.ajax({
                url: url,
                type: "post",
                data: data,
                success: callback
            });
        }

        function delFileEmbargo(id, uid, docid){
            $.ajax({
                type: "POST",
                url: '/moderate/ajaxdelfileembargo',
                data: {id : id, uid: uid, docid:docid},
                success: function(data){
                    $('#file'+id).replaceWith(data);
                }
            });
        }

        $('input').on("focus", function() {
            $(this).keyup(function (e) {
                if (e.keyCode == 13 && $(this).val() != '') {
                    window.location.replace("<?php echo PREFIX_URL."moderate/embargo?query"?>" + $(this).attr("id") + "=" + $(this).val());
                } else if (e.keyCode == 13){
                    window.location.replace("<?php echo PREFIX_URL."moderate/embargo"?>");
            }
            });
        });
    </script>
<?php } else { ?>
    <div class="alert alert-success"><strong><?php echo $this->translate("Aucun dépôt ne correspond à la recherche :)");?></strong></div>
<?php } ?>