-- requetes SQL pour modification BdD pour Laboratoire User
-- table USER

ALTER TABLE USER ADD COLUMN LABORATORY_OLD VARCHAR(255) NULL AFTER DEFAULT_AUTHOR;

UPDATE USER SET LABORATORY_OLD = LABORATORY;

UPDATE USER SET LABORATORY = '';