-- Ajout de 2 colonnes dans la table Doc_Metadata
-- table DOC_METADATA

SELECT '!!!!!!!!! - ATTENTION, IL FAUDRA SUPPRIMER LE CACHE DES DOCUMENTS - !!!!!!!!!';
SELECT '!!!!!!!!! find /cache/hal/testing/docs -name "*.phps" | xargs rm                   !!!!!!!!!';

ALTER TABLE `DOC_METADATA` ADD `SOURCE` VARCHAR(25) NOT NULL DEFAULT 'web' AFTER `METAGROUP`;
ALTER TABLE `DOC_METADATA` ADD `UID` INT NOT NULL DEFAULT '0' AFTER `SOURCE`;

ALTER TABLE `DOC_HASCOPY` ADD `SOURCE` VARCHAR(25) NOT NULL DEFAULT 'web' AFTER `LOCALID`;
ALTER TABLE `DOC_HASCOPY` ADD `UID` INT NOT NULL DEFAULT '0' AFTER `SOURCE`;
