--
-- Structure de la table `DOC_LINKEXT`
--

CREATE TABLE `DOC_LINKEXT` (
  `LINKEXTID` int(11) UNSIGNED NOT NULL,
  `LINKID` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `URL` varchar(500) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Index pour la table `DOC_LINKEXT`
--
ALTER TABLE `DOC_LINKEXT`
  ADD PRIMARY KEY (`LINKEXTID`),
  ADD UNIQUE KEY `LINKID` (`LINKID`) USING BTREE,
  ADD KEY `URL` (`URL`(100)) USING BTREE;

--
-- AUTO_INCREMENT pour la table `DOC_LINKEXT`
--
ALTER TABLE `DOC_LINKEXT`
  MODIFY `LINKEXTID` int(11) UNSIGNED NOT NULL AUTO_INCREMENT;