-- Ajout de la table USER_PREF_MAIL

CREATE TABLE `USER_PREF_MAIL` (
  `PREFMID` int(25) NOT NULL AUTO_INCREMENT,
  `UID` int(25) NOT NULL,
  `RIGHTID` varchar(20) NOT NULL,
  `STRUCTID` int(25) NULL,
  `SEND` tinyint(1) NOT NULL,
   PRIMARY KEY (`PREFMID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

