CREATE TABLE `DB_PATCHES` ( `FILE` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL , `DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ) ENGINE = InnoDB;
UPDATE SITE SET ID="hal-" WHERE SITE.SITE = 'cel' OR SITE.SITE = 'medihal';

-- Patche mark as applied: must be elsewhere... but now...
INSERT INTO DB_PATCHES  (`FILE`) VALUES ('2019-07-12.sql');
