-- requetes SQL pour modification BdD pour modération
-- table USER

ALTER TABLE USER ADD COLUMN NBDOCVIS INT NOT NULL DEFAULT 0 AFTER DOMAIN;

ALTER TABLE USER ADD COLUMN NBDOCSCI INT NOT NULL DEFAULT 0 AFTER DOMAIN;

ALTER TABLE USER ADD COLUMN NBDOCREF INT NOT NULL DEFAULT 0 AFTER DOMAIN;