<?php if ($this->templates) : ?>
<div id="templates">
<?php foreach ($this->templates as $template) : ?>
	<div style="border-bottom: 1px solid #aaa; padding-bottom: 6px; margin-bottom: 4px; clear: both">
		<a 	class="modal-opener"
			title="<?php echo $this->translate('Modifier ce template'); ?>"
			href="/administratemail/edittemplate?id=<?php echo $template['ID']?>">
    		<?php echo $this->translate($template['KEY'].'_tpl_name')?>
    	</a>
    	
	    <div style="float: right">
	    	<a 	class="modal-opener" 
	    		href="/administratemail/edittemplate?id=<?php echo $template['ID']?>"
	    		title="<?php echo $this->translate('Modifier ce template');?>"><button class="btn btn-default btn-xs" data-toggle="tooltip" title="<?php echo $this->translate('Modifier ce template');?>"><span class="glyphicon glyphicon-edit"></span></button></a>	
	    	<?php if ($template['PARENTID']) : ?>
	    	<a	class="delete-template" 
	    		href="/administratemail/deletetemplate?id=<?php echo $template['ID']?>"
	    		title="<?php echo $this->translate('Revenir au template par défaut');?>">
	    		<button class="btn btn-default btn-xs" data-toggle="tooltip" title="<?php echo $this->translate('Revenir au template par défaut');?>"><span class="glyphicon glyphicon-share-alt rotation-180"></span></button></a>
	    	<?php else : ?>
	    	<button class="btn btn-default btn-xs disabled"><span class="glyphicon glyphicon-share-alt rotation-180"></span></button>
	    	<?php endif;?>
	    	
	    </div>	
    </div>
<?php endforeach;?>
</div>
<?php
	// Modal box (contient le formulaire de modification de template)
	$this->jQuery()->addJavascriptFile('/js/administratemail/templates.js');
	$style = array('width'=>'50%');
	echo $this->partial('partials/modal.phtml', array('style'=>$style)); 
?>

<?php endif; ?>
<?php 
	$this->jQuery()->addJavascriptFile("/js/urlParser.js");
	$this->jQuery()->addJavascriptFile(CCSDLIB . "/js/tinymce/jquery.tinymce.min.js");
	$this->jQuery()->addJavascriptFile(CCSDLIB . "/js/tinymce/tinymce.min.js");
	$this->jQuery()->addJavascriptFile(CCSDLIB ."/js/tinymce_patch.js");
	$this->jQuery()->addJavascriptFile(CCSDLIB . "/js/bootbox.min.js");
?>