<?php
/**
 * Vue d'un document en administration (étape récap ou modération ou validation)
 * User: yannick
 * Date: 26/05/2014
 * Time: 11:01
 */
if (! (isset($this->document) && $this->document instanceof Hal_Document) ) {
    exit();
}
?>
<table class="meta table table-condensed table-bordered">
    <tbody>
    <tr>
        <td class="meta-name" style="width:150px;"><?php echo $this->translate('Format du dépôt'); ?></td>
        <td colspan="2"><span class="label label-default"><?php echo $this->translate('format_' . $this->document->getFormat()); ?></span></td>
    </tr>
    <tr>
        <td class="meta-name" style="width:150px;"><?php echo $this->translate('Type de document'); ?></td>
        <td colspan="2"><span class="<?php echo Hal_Settings::getLabelClassName($this->document->getTypdoc()); ?>"><?php echo $this->translate('typdoc_' . $this->document->getTypdoc()); ?></span></td>
    </tr>
    <?php
    $title = $this->document->getTitle();
    if (! is_array($title)) {
        $title = array($title);
    }
    $i = 0;
    foreach($title as $lang => $value) {?>
        <tr>
            <?php if ($i == 0) { ?>
                <td <?php echo count($title)>1 ? 'rowspan="' . count($title) . '"' : '' ?> class="meta-name"><?php echo $this->translate('Titre'); ?></td>
            <?php } ?>
            <td style="width:30px;"><span class="label label-default"><?php echo $this->translate($lang); ?></span></td>
            <td><h5 style="margin:0;"><?php echo $value ?></h5></td>
        </tr>
        <?php
        $i++;
    }
    $subtitle = $this->document->getSubTitle();
    if (! is_array($subtitle)) {
        $subtitle = array($subtitle);
    }
    $i = 0;
    foreach($subtitle as $lang => $value) {?>
        <tr>
            <?php if ($i == 0) { ?>
                <td <?php echo count($subtitle)>1 ? 'rowspan="' . count($subtitle) . '"' : '' ?> class="meta-name"><?php echo $this->translate('Sous-Titre'); ?></td>
            <?php } ?>
            <td style="width:30px;"><span class="label label-default"><?php echo $this->translate($lang); ?></span></td>
            <td><h5 style="margin:0;"><?php echo $value ?></h5></td>
        </tr>
        <?php
        $i++;
    } ?>
    <tr>
        <td rowspan="2" class="meta-name"><?php echo $this->translate('Auteur(s)'); ?></td>
        <td colspan="2">
            <?php $corresponding = false;
            $authors = $this->document->getAuthors();
            ?>
            <?php foreach ($authors as $i => $author) { ?>
                <?php $tooltip = $this->translate('relator_' . $author->getQuality()) . '<br>';

                if ($author->getEmail() != '') {
                    $tooltip .= $this->translate('Mail') . ': ' . $author->getEmail() . '<br>';
                }
                if ($author->getIdHal() != 0) {
                    $tooltip .= $this->translate('IdHAL') . ': ' . $author->getIdhalstring() . ' (' . $author->getIdHal() .')<br>';
                }
                if ($author->getOrganism() != '') {
                    $tooltip .= $this->translate("Établissement d'appartenance") . ': ' . $author->getOrganism() .'<br>';
                }
                ?>

                <strong data-toggle="tooltip" title="<?php echo $tooltip ?>"><?php echo $author->getFullname(true); ?></strong>
                <?php
                $structids = $author->getStructidx();
                foreach ($structids as &$idx) {
                    $idx += 1;
                }
                if ($author->getQuality() =='crp') {
                    $corresponding = true;
                    $structids[] = '*';
                } ?>
                <?php if (count($structids)) { ?>
                    <sup><?php echo implode(', ', $structids) ?></sup>
                <?php }

                if ($i < (count($authors) - 1)) {
                    echo ", ";
                }
            } ?>
            <?php if ($corresponding) { ?>
                <div class="corresponding">* : <?php echo $this->translate('Auteur correspondant'); ?></div>
            <?php } ?>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <?php foreach ($this->document->getStructures() as $i => $struct) { ?>
                <div class="struct">
                    <span class="structid label label-default"><?php echo $i + 1; ?></span>
                    <strong>
                        <?php if ($struct->getSigle()) {?>
                            <?php echo $struct->getSigle() . ' - '; ?>
                        <?php } ?>
                        <?php echo  $struct->getStructname() . ' <span class="label label-default">' . $struct->getStructid() . '</span> - '; ?>
                    </strong>
                    <?php if ($struct->getAddress() != '') {?>
                        <?php echo $struct->getAddress(); ?>&nbsp;-&nbsp;
                    <?php } ?>
                    <?php $country = Zend_Locale::getTranslation(strtoupper($struct->getPaysid()), 'country');
                    if ($country == '') {$country = strtoupper($struct->getPaysid());}
                    echo $country; ?><br>
                    <?php
                    $parents = array();
                    foreach ($struct->getAllParents() as $parent) {
                        $code = Ccsd_Tools::ifsetor($parent['code']);
                        $parents[] = $parent['struct']->getStructname() . ($code != '' ? ' : ' . $code : '') . ' <span class="label label-default">' . $parent['struct']->getStructId() . '</span>';
                    }
                    if (count($parents)) {
                        ?> <span class="prec"> <?php echo implode(' ; ', $parents); ?> </span><?php
                    }
                    ?>
                </div>
            <?php } ?>
        </td>
    </tr>
    <?php
    $abstract = $this->document->getAbstract();
    if (! is_array($abstract)) {
        $abstract = array($abstract);
    }
    $i = 0;
    foreach($abstract as $lang => $value) {?>
        <tr>
            <?php if ($i == 0) { ?>
                <td <?php echo count($abstract)>1 ? 'rowspan="' . count($abstract) . '"' : '' ?> class="meta-name"><?php echo $this->translate('Résumé'); ?></td>
            <?php } ?>
            <td><span class="label label-default"><?php echo $this->translate($lang); ?></span></td>
            <td class="linkify" style="text-align:justify;"><?php echo $value ?></td>
        </tr>
        <?php
        $i++;
    }

    foreach($this->document->getIdsCopyUrl() as $server => $value) {?>
        <tr>
            <td class="meta-name"><?php echo $this->translate($server); ?></td>
            <td colspan="2">
                <a href="<?php echo $value['link'] ?>" target="_blank"><?php echo $value['id'] ?></a>
            </td>
        </tr>
        <?php
        $i++;
    }
    $metaslabels = Hal_Settings::getMeta($this->document->getTypdoc());
    $metasList = Hal_Referentiels_Metadata::metaList();
    foreach($this->document->getMeta() as $meta => $value) {
        if (in_array($meta, array_keys($metaslabels['elements']))){
        if ($meta != 'licence'){
            $metalabel = $metaslabels['elements'][$meta]['options']['label'];
        }
        if (in_array($meta, array('title', 'subTitle', 'abstract', 'identifier', 'inPress', 'watermark'))) continue;

        $linkify = in_array($meta, array('seeAlso'));

        if (! is_array($value)) {
            if ($value == null || $value == '') continue;
            $value = array($value);
        }
        $i = 0;
        foreach($value as $key => $v) {
            if ($v == '' || $v == null) continue;
            ?>
            <tr>
                <?php if ($i == 0) { ?>
                    <td <?php echo count($value)>1 ? 'rowspan="' . count($value) . '"' : '' ?> class="meta-name"><?php if ($meta != 'licence'){echo $this->translate($metalabel);} else {echo 'licence';} ?></td>
                <?php } ?>
                <?php if (Hal_Settings::isMultiLanguageMetas($meta)) { ?>
                <td><span class="label label-default"><?php echo $this->translate($key); ?></span></td>
                <td <?php echo ($linkify ? 'class="linkify"' : '') ?>>
                    <?php }  else {?>
                <td colspan="2" <?php echo ($linkify ? 'class="linkify"' : '') ?>>
                    <?php } ?>
                    <?php
                    if (is_array($v)) {
                        echo implode(", ", $v);
                    } else if (in_array($meta, array('domain', 'acm', 'acm2012', 'pacs', 'jel', 'domain_inter', 'otherType'))) {
                        if (preg_match('/domain_inter/',$meta)) {
                            $meta = preg_replace('/domain_inter/','domain',$meta);
                            $i++;
                        }
                        $v = Ccsd_Tools_String::getHalMetaTranslated($v, null, '/', $meta, true);
                        if ($i == 0) {
                            $v = '<strong>' .$v . '</strong>';
                        }
                        echo $v;
                    } else if ($meta == 'language' || $meta == 'country') {
                        $v = $meta == 'language' ? strtolower($v) : strtoupper($v);
                        $tmp = Zend_Locale::getTranslation($v, $meta);
                        echo ($tmp != '') ? $tmp : $v;
                    } else if (in_array($meta, ['campusaar_classaar', 'campusaar_genre', 'campusaar_context'])) {
                        echo $this->translate($v);
                    } else if (in_array($meta, $metasList)) {
                        echo $this->translate(Hal_Referentiels_Metadata::getLabel($meta, $v));;
                    } else if ($meta == 'date') {
                        if ($this->document->getMeta('inPress')) {
                            echo $this->translate('inPress');
                        } else {
                            echo $v;
                        }
                    } else if ($meta == 'circa') {
                        if ($v) {
                            echo $this->translate('Oui');
                        } else {
                            echo $this->translate('Non');
                        }
                    } else if ($meta == 'researchdata') {
                        echo "<a href=\"".Hal_Document_Meta_Researchdata::getDataUrl($v)."\" target=\"_blank\" type=\"noopener\">".$v."</a>";
                    } else {
                        echo $v;
                    }?></td>
            </tr>
            <?php $i++;
        } ?>
    <?php }}

    if (!$this->hideFiles) {
        $files = $this->document->getFiles();
        if (count($files)) {
            $i = 0;
            $this->showType = true;
            $this->readEmbargo = true;
            foreach($files as $id => $file) {
                $this->file = $file;
                $this->href = (isset($this->filesInTmpDir) && $this->filesInTmpDir) ? '/file/tmp/fid/' . $id : '/file/index/docid/' . $this->document->getDocid() . '/filename/' . rawurlencode($file->getName());

                ?>
                <tr>
                    <?php if ($i == 0) { ?>
                        <td <?php echo count($files)>1 ? 'rowspan="' . count($files) . '"' : '' ?> class="meta-name"><?php echo $this->translate('Fichier(s)'); ?></td>
                    <?php } ?>
                    <td colspan="2">
                        <?php  include 'row-file.phtml' ;?>
                    </td>
                </tr>
                <?php
                $i++;
            }
        }
    }
    ?>
    </tbody>
</table>
<?php if ($this->showHistory) { ?>
    <div class="panel panel-default" id="history-<?php echo $this->document->getDocid() ?>">
        <div class="panel-heading" role="tab" id="headingOne">
            <div class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" onclick="getDocHistory('<?php echo $this->document->getDocid() ?>', '#history-<?php echo $this->document->getDocid() ?>')">
                    <i class="glyphicon glyphicon-calendar"></i>&nbsp;<?php echo $this->translate('Historique du dépôt'); ?>
                </a>
            </div>
        </div>
        <div id="collapseOne" class="panel-collapse collapse <?php echo ($this->moderate ? 'in': '') ?>" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body result">
            </div>
        </div>
    </div>
    <?php if (($this->moderate) OR ($this->validate)) { ?>
        <script type="text/javascript">
            $(function() {getDocHistory('<?php echo $this->document->getDocid() ?>', '#history-<?php echo $this->document->getDocid() ?>');});
        </script>
    <?php } ?>
<?php } ?>
