<?php
$this->headLink(['rel'=>'schema.DC', 'href'=>'http://purl.org/dc/elements/1.1/']);

$language = $this->document->getMeta('language');
$this->headMeta()->prependName('citation_language', $language);
$this->headMeta()->prependName('DC.language', $language);

$typeDC = array('UNDEFINED'=>'document', 'ART'=>'journal', 'OUV'=>'book', 'COUV'=>'incollection', 'COMM'=>'proceedings', 'POSTER'=>'poster', 'REPORT'=>'report', 'THESE'=>'phdthesis', 'HDR'=>'thesis', 'LECTURE'=>'lecture', 'IMG'=>'image', 'VIDEO'=>'video', 'PATENT'=>'patent', 'DOUV'=>'book', 'SON'=>'sound');
$this->headMeta()->prependName('DC.type', array_key_exists($this->document->getTypDoc(), $typeDC) ? $typeDC[$this->document->getTypDoc()] : 'other');
$this->headMeta()->prependProperty('og:type', array_key_exists($this->document->getTypDoc(), $typeDC) ? $typeDC[$this->document->getTypDoc()] : 'other');

$title = $this->document->getMainTitle();
$this->headTitle($title);
$this->headMeta()->prependName('citation_title', $title);
$this->headMeta()->prependName('DC.title', $title);
$this->headMeta()->prependProperty('og:title', $title);

$this->headMeta()->prependName('DC.identifier', $this->document->getUri());
$this->headMeta()->prependName('DC.identifier', $this->document->getId());
$this->headMeta()->prependProperty('og:url', $this->document->getUri());

$authors = $this->document->getAuthors();
if (count($authors)) {
	$authors = array_reverse($authors);
    foreach ($authors as $author) {
        $fullName = $author->getFullname();
        $this->headMeta()->prependName('citation_author', $fullName);
        $this->headMeta()->prependName('DC.creator', $fullName);
    }
}

$abstract = $this->document->getAbstract($language);
if ( $abstract == '' || is_array($abstract) ) {
    $abstract = $this->document->getAbstract();
    if ( count($abstract) ) {
        $abstract = array_values($abstract)[0];
    } else {
        $abstract = '';
    }
}
if ( $abstract ) {
    $this->headMeta()->prependName('citation_abstract', $abstract);
    $this->headMeta()->prependName('DC.description', $abstract);
    $this->headMeta()->prependName('description', $abstract);
    $this->headMeta()->prependProperty('og:description', $abstract);
}

$keywords = $this->document->getKeywords();
if (count($keywords)) {
    foreach ($keywords as $lang => $words) {
        if (! is_array($words)) {
            $words = array(
                    $words
            );
        }
        $keywordList = implode(' ; ', $words);
        $this->headMeta()->prependName('citation_keywords', $keywordList);
        $this->headMeta()->prependName('DC.subject', $keywordList);
        $this->headMeta()->prependName('keywords', $keywordList);
    }
}

$default = $this->document->getDefaultFile();
if ($default != false && $default != null && $default->canRead()) {
    $url = $this->document->getUri() . '/document';
    $this->headMeta()->prependName('citation_pdf_url', $url);
    $this->headMeta()->prependName('DC.identifier', $url);
    $this->headMeta()->prependProperty('og:url', $url);
}

$this->headMeta()->prependName('citation_online_date', $this->document->getSubmittedDate('yyyy/MM/dd'));
$l = strlen($this->document->getProducedDate());
$format = 'yyyy';
if ( $l > 8 ) {
    $format = 'yyyy/MM/dd';
} else if ( $l > 5 ) {
    $format = 'yyyy/MM';
}
$this->headMeta()->prependName('citation_publication_date', $this->document->getProducedDate($format));
$this->headMeta()->prependName('DC.date', $this->document->getProducedDate($format));
$this->headMeta()->prependName('DC.issued', $this->document->getProducedDate($format));

foreach ($this->document->getMeta() as $meta => $value) {
    if ((is_array($value) && count($value) == 0) || $value == '') continue;
    switch ($meta) {
        case 'journal':
            $this->headMeta()->prependName('citation_journal_title', $value->JNAME);
            $this->headMeta()->prependName('DC.relation.ispartof', $value->JNAME);
            break;

        case 'bookTitle':
            $this->headMeta()->prependName('DC.relation.ispartof', $value);
            break;

        case 'identifier':
            foreach ($value as $i=>$v) {
                if ( $i == 'doi' ) {
                    $this->headMeta()->prependName('citation_doi', $v);
                } else if ( $i == 'pubmed' ) {
                    $this->headMeta()->prependName('citation_pmid', $v);
                } else {
                    $this->headMeta()->prependName('citation_id', $v);
                }
            }
            break;

        case 'page':
            $this->headMeta()->prependName('citation_firstpage', $value);
            break;

        case 'conferenceTitle':
            $this->headMeta()->prependName('citation_conference_title', $value);
            $this->headMeta()->prependName('DC.relation.ispartof', $value);
            break;

        case 'volume':
            $this->headMeta()->prependName('citation_volume', $value);
            $this->headMeta()->prependName('DC.citation.volume', $value);
            break;

        case 'issue':
            $this->headMeta()->prependName('citation_issue', $value);
            $this->headMeta()->prependName('DC.citation.issue', $value);
            break;

        case 'issn':
            $this->headMeta()->prependName('citation_issn', $value);
            break;

        case 'eissn':
            $this->headMeta()->prependName('citation_issn', $value);
            break;

        case 'isbn':
            $this->headMeta()->prependName('citation_isbn', $value);
            break;

        case 'publisher':
            $this->headMeta()->prependName('DC.publisher', is_array($value) ? implode(' ; ', $value) : $value);
            break;

        case 'authorityInstitution':
            $this->headMeta()->prependName('citation_dissertation_institution', is_array($value) ? implode(' ; ', $value) : $value);
            $this->headMeta()->prependName('DC.publisher', is_array($value) ? implode(' ; ', $value) : $value);
            break;
    }
}