<?php
/**
 * Created by PhpStorm.
 * User: iguay
 * Date: 24/04/2019
 * Time: 09:42
 *
 * $this->document doit exister et etre un objet Hal_Document
 *
 */

?>
<div class="widget widget-citation">
    <h3 class="widget-header"><?php echo $this->translate('Citer') ?></h3>
    <div class="widget-content ref-biblio">
        <?php $values =  $this->document->getReuse();
        if (isset($values)) { ?>
        <?php echo $this->document->getMainTitle().'. <br> '.
                Ccsd_Tools::ifsetor($values['auteur'], $values['auteur'], '').' <br> '.
                Zend_Registry::get('Zend_Translate')->translate('Document original téléchargé depuis')
            .' <a href = "'. $this->document->getUri(true). '">'.$this->document->getUri().' </a> '.Zend_Registry::get('Zend_Translate')->translate(' mise à jour du').' '.$values['datePubli']; ?>
            © <a href = https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf>Licence ouverte v 2.0</a>
        <?php } ?>

    </div>
</div>
