<?php
/**
 * Created by PhpStorm.
 * User: iguay
 * Date: 24/04/2019
 * Time: 09:42
 *
 * $this->document doit exister et etre un objet Hal_Document
 *
 */

?>
<div class="widget widget-citation">
    <h3 class="widget-header"><?php echo $this->translate('Citer') ?></h3>
    <div class="widget-content ref-biblio">
        <?php $values =  $this->document->getReuse();
        if (isset($values)) { ?>
        <?php echo $this->document->getMainTitle().' - '.Ccsd_Tools::ifsetor($values['auteur'], $values['auteur'], '').Ccsd_Tools::ifsetor($values['arboEntites'], $values['arboEntites'], '').' - '.Zend_Registry::get('Zend_Translate')->translate('Données originales téléchargées depuis')
            .' <a href = "'. $this->document->getUri(true). '">'.$this->document->getUri().' </a> '.Zend_Registry::get('Zend_Translate')->translate('mise à jour du').' '.$values['datePubli']; ?>
        <br>© Licence ouverte / open licence
        <?php } ?>

    </div>
</div>
