<?php
/**
 * Created by PhpStorm.
 * User: yannick
 * Date: 26/09/2014
 * Time: 09:42
 *
 * $this->document doit exister et etre un objet Hal_Document
 *
 */

if (count($this->document->getRelated())) { ?>
    <div class="widget widget-relations">
        <h3 class="widget-header"><?php echo $this->translate('Relations') ?></h3>
        <div class="widget-content">
            <ul>
                <?php foreach ($this->document->getRelated() as $related) { ?>
                    <li><?php echo $this->translate('relatedType_'.$related['RELATION']) ?> <strong><a href="<?php echo $related['URI'] ?>" target="_blank" rel="noopener"><?php echo basename($related['URI']) ?></a></strong><?php echo ($related['INFO'] ? ' - ' . $related['INFO'] : '' )  ?></li>
                <?php } ?>
            </ul>
        </div>
    </div>
<?php }
