<?php
/**
 * Created by PhpStorm.
 * User: yannick
 * Date: 26/09/2014
 * Time: 09:42
 *
 * $this->document doit exister et etre un objet Hal_Document
 *
 */
?>

<?php if ($rd = $this->document->getHalMeta()->getHalMeta("researchdata")) { ?>
<div class="widget widget-data">
    <h3 class="widget-header"><?php echo $this->translate('Données associées') ?></h3>
    <div class="widget-content">
        <ul>
            <?php foreach($rd->getValue() as $v) {?>
            <li><a href="<?php echo Hal_Document_Meta_Researchdata::getDataUrl($v);?>" target="_blank" rel="noopener"><?php echo $v ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php } ?>