<?php
/**
 * Created by PhpStorm.
 * User: yannick
 * Date: 26/09/2014
 * Time: 09:42
 *
 * $this->document doit exister et etre un objet Hal_Document
 *
 */

$uri = '/' . $this->document->getId() . 'v' . $this->document->getVersion(); ?>

<div class="widget widget-export">
    <h3 class="widget-header"><?php echo $this->translate('Exporter') ?></h3>
    <div class="widget-content" style="text-align:center">
        <a class="widget-export-btn btn btn-default btn-sm" href="<?php echo $uri . '/bibtex'  ?>" role="button" target="_blank">BibTeX</a>
        <a class="widget-export-btn btn btn-default btn-sm" href="<?php echo $uri . '/tei'     ?>" role="button" target="_blank">TEI</a>
        <a class="widget-export-btn btn btn-default btn-sm" href="<?php echo $uri . '/dc'      ?>" role="button" target="_blank">DC</a>
        <a class="widget-export-btn btn btn-default btn-sm" href="<?php echo $uri . '/dcterms' ?>" role="button" target="_blank">DCterms</a>
        <a class="widget-export-btn btn btn-default btn-sm" href="<?php echo $uri . '/endnote' ?>" role="button">EndNote</a>
    </div>
</div>
