<?php
/**
 * Created by PhpStorm.
 * User: yannick
 * Date: 26/09/2014
 * Time: 09:42
 *
 * $this->document doit exister et etre un objet Hal_Document
 *
 */
?>

<div class="widget widget-identifiants">
    <h3 class="widget-header"><?php echo $this->translate('Identifiants') ?></h3>
    <div class="widget-content">
        <ul>
            <?php if (Hal_Auth::isHALAdministrator()) {?>
                <li>DOCID : <strong><?php echo $this->document->getDocid(); ?></strong></li>
            <?php } ?>
            <li>HAL Id : <strong><?php echo $this->document->getId(); ?>, <?php echo $this->translate('version') . ' ' . $this->document->getVersion();?></strong></li>
            <?php if (Hal_Auth::getUid() == $this->document->getContributor('uid')) {?>
                <li><?php echo $this->translate('Mot de passe'); ?> : <strong><?php echo $this->document->getPwd(); ?></strong></li>
            <?php } ?>
            <?php $copy = $this->document->getIdsCopyUrl();?>
            <?php if (count($copy)) {?>
                <?php foreach ($copy as $server => $id) { ?>
                    <li><?php echo $this->translate(strtoupper($server)) ?> : <strong>
                    <?php if ($id['link']!=$id['id']) {?><a href="<?php echo $id['link'] ?>" target="_blank"><?php echo $id['id'] ?></a><?php } else { echo $id['id']; } ?>
                    </strong></li>
                <?php } ?>
            <?php } ?>
        </ul>
    </div>
</div>
