<?php

$fileName = 'legalnotice';
$localDir = SPACE . PUBLIC_DEF;
$defaultDir = APPROOT . '/' . CONFIG . 'html/';
try {
    $lang = Zend_Registry::get('lang');
} catch (Zend_Exception $e) {
    $lang = 'fr';
}

$localFile = $localDir . $fileName . '.' . $lang . '.html';
$defaultFile = $defaultDir . $fileName . '.' . $lang . '.html';

if (is_file($localFile)) { //Fichier specifique au portail
    $toIncludeFile = $localFile;
} else if (is_file($defaultFile)) {
    $toIncludeFile = $defaultFile;
} else {
    $toIncludeFile = null;
}
?>
<div class="content">
    <?php if ($toIncludeFile !== null) {
        include($toIncludeFile);
    } ?>
</div>