Dear %%USER%%,

We are sending password reset instructions to this email address upon your request.

You must click on the following link to reset your password:

<a href='%%TOKEN_VALIDATION_LINK%%'>%%TOKEN_VALIDATION_LINK%%</a>

If you did not request these instructions, you can safely ignore this message.
For instance, someone may have done a mistake when entering his username.

Sincerely yours,

--
The %%PORTAIL%%/CCSD team

