Dear %%USER%%,

This automatic message informs you of the new online documents corresponding to your alert : %%ALERT_NAME%%.
The frequency of you alert is : %%ALERT_FREQ%%

There are %%ALERT_NUM_DOCS%% documents corresponding to your subscription criteria.
Here is the link to access your research : %%ALERT_SEARCH_URL%%
You can modify your alerts on : https://hal.archives-ouvertes.fr/user/search

%%ALERT_DOC_LIMIT%%
------------------------------------------------------------------------------
%%ALERT_DOC_LIST%%
------------------------------------------------------------------------------

--
%%PORTAIL%%/CCSD Team
