Dear %%USER%%,

Thank you for your expertise on the document %%DOC_ID%% on %%PORTAIL%% ( %%PORTAIL_URL%% ).

This submission is back to moderation with your review and the moderators have been informed by email.

------------------------------------------------------------------------------
ID             : %%DOC_ID%%
url            : %%DOC_URL%% (you have to login before accessing this url)
version        : %%DOC_VERSION%%
contributor    : %%DOC_CONTRIBUTOR%%
submission date: %%DOC_DATE%%
title          : %%DOC_TITLE%%
author(s)      : %%DOC_AUTHORS%%
laboratorie(s) : %%DOC_LABOS%%
domain(s)      : %%DOC_DOMAINS%%
------------------------------------------------------------------------------

Thank you again for your expertise,
Have a good day,

--
%%PORTAIL%% Team
HAL CCSD
