Dear %%USER%%,

This message is a reminder. There is a new submission to be evaluated on %%PORTAIL%% ( %%PORTAIL_URL%% ).

------------------------------------------------------------------------------
id             : %%DOC_ID%%
url            : %%DOC_URL%% (you have to login before accessing this url)
version        : %%DOC_VERSION%%
contributor    : %%DOC_CONTRIBUTOR%%
submission date: %%DOC_DATE%%
title          : %%DOC_TITLE%%
author(s)      : %%DOC_AUTHORS%%
laboratorie(s) : %%DOC_LABOS%%
domain(s)     : %%DOC_DOMAINS%%
------------------------------------------------------------------------------

Thank you for your expertise.
Greetings,

-----------------
%%PORTAIL%% Team
HAL CCSD
