Dear %%USER%%,

It is the end of the evaluation period on the document %%DOC_ID%% on %%PORTAIL%% ( %%PORTAIL_URL%% ).

This submission is not to be evaluated anymore.

------------------------------------------------------------------------------
id             : %%DOC_ID%%
url            : %%DOC_URL%% (you have to login before accessing this url)
version        : %%DOC_VERSION%%
contributor    : %%DOC_CONTRIBUTOR%%
submission date: %%DOC_DATE%%
title          : %%DOC_TITLE%%
author(s)      : %%DOC_AUTHORS%%
laboratorie(s) : %%DOC_LABOS%%
domain(s)      : %%DOC_DOMAINS%%
------------------------------------------------------------------------------

Greetings,
--
%%PORTAIL%% Team
HAL CCSD
