Dear %%USER%%,

New submission on %%PORTAIL%% ( %%PORTAIL_URL%% ).
New submission on the portal ( %%PORTAIL%% %%PORTAIL_URL%% ).

------------------------------------------------------------------------------
ID : %%DOC_ID%%
version : %%DOC_VERSION%%
contributor : %%DOC_CONTRIBUTOR%%
submission date : %%DOC_DATE%%
title : %%DOC_TITLE%%
author(s) : %%DOC_AUTHORS%%
laboratorie(s) : %%DOC_LABOS%%
domain (s) : %%DOC_DOMAINS%%
------------------------------------------------------------------------------

Please check the document by login on %%PORTAIL_URL%%

-----------------
%%PORTAIL%%/CCSD Team 
