Dear %%USER%%,

New submission on %%PORTAIL%% ( %%PORTAIL_URL%% ).

------------------------------------------------------------------------------
ID : %%DOC_ID%%
version : %%DOC_VERSION%%
contributor : %%DOC_CONTRIBUTOR%%
submission : %%DOC_DATE%%
type of document : %%DOC_TYPDOC%%
title : %%DOC_TITLE%%
author(s) : %%DOC_AUTHORS%%
laboratorie(s) : %%DOC_LABOS%%
domain(s) : %%DOC_DOMAINS%%
------------------------------------------------------------------------------

Please check the document by login on %%PORTAIL_URL%%

-----------------
%%PORTAIL%%/CCSD Team
