Dear %%USER%%,

A request of property share was made on your document %%DOC_ID%% ( <a href='%%DOC_URL%%'>%%DOC_URL%%</a> ).

title     : %%DOC_TITLE%%
author(s) : %%DOC_AUTHORS%%

Here is the request of %%REQUEST_USER%% (%%REQUEST_USER_EMAIL%%) :
%%REQUEST_MESSAGE%%

To satisfy this request, you have to go to %%PORTAIL%% ( %%PORTAIL_URL%% ) on the page "My space > My shared ownership"

Greetings,

-----------------
%%PORTAIL%%/CCSD Team