Dear %%USER%%,

    The information regarding your new submission on HAL portal (%%PORTAIL%% <a href="%%DOC_URL%%">%%DOC_URL%%</a> ) is:

%%DOC_REF%%
------------------------------------------------------------------------------
id : %%DOC_ID%%
version : %%DOC_VERSION%%
password : %%DOC_PWD%%
submission date : %%DOC_DATE%%
------------------------------------------------------------------------------

This information will be necessary during your future modifications of this article.

Greetings,

-----------------
The HAL %%PORTAIL%%/CCSD team

P.S: the document has to be indexed by our machines. Until the document has been processed by our indexing server, you may see a page 'Document not accessible' by clicking on the link above.