Dear %%USER%%,

%%REQUEST_USER%% (%%REQUEST_USER_EMAIL%%) would like to have access to the full-text (%%DOC_FILENAME%%) associated to your deposit %%DOC_ID%%, version %%DOC_VERSION%%, which is currently under embargo.

In order to answer this query, please:

1- Go to %%PORTAIL%% ( %%PORTAIL_URL%% ) and further to “My space / My shared embargoed documents“
Or
2- click on one of the following links:
    * <a href='%%REQUEST_URL%%/user/filerequest/docid/%%DOCID%%/uid/%%REQUEST_UID%%/accept/1'>to grant access to your file</a> ;
    * <a href='%%REQUEST_URL%%/user/filerequest/docid/%%DOCID%%/uid/%%REQUEST_UID%%/accept/0'>to deny access to your file</a>.


Sincerely yours,

---
The %%PORTAIL%%/CCSD team
HAL CCSD