Dear %%USER%%,

This message is a reminder.

In order to put your submission online, please make the following corrections to your document %%DOC_ID%%, version %%DOC_VERSION%% by logging into %%PORTAIL%% ( %%PORTAIL_URL%% )
---
%%MSG_MODERATEUR%%
---

You can use the "Modify" ou the "Answer" actions in the the menu "Documents waiting for modifications" in "My deposits" space.

Greetings,

-----------------
The %%PORTAIL%% team
HAL CCSD