Dear %%USER%%,

The information regarding your new submission on %%PORTAIL%% ( <a href="%%DOC_URL%%">%%DOC_URL%%</a> ) is :

%%DOC_REF%%
------------------------------------------------------------------------------
id : %%DOC_ID%%
version : %%DOC_VERSION%%
password : %%DOC_PWD%%
submission date : %%DOC_DATE%%
------------------------------------------------------------------------------

This information will be necessary during your future modification of this article.
The document will now be evaluated: file(s) will be checked, metadatas, etc.

Greetings,

-----------------
The %%PORTAIL%%/CCSD team