%%MAIL_TO_FULLNAME%%,

You have been recognized as author of this new document on HAL :

<a href='%%DOCUMENT_URL%%' style="color:#292063;">%%DOC_REF%%</a>

Are you indeed author of this document ? <a href='%%OWNERSHIP_KO_URL%%' style="border:solid #292063 1px; border-radius:4px; padding:2px; color:white; background-color: #292063;">NO</a>  <a href='%%OWNERSHIP_OK_URL%%' style="color:#292063;">YES</a>

As authors of this publication, you have the property rights. You can complete metadatas, add a file or a new version of the document.

Greetings,
--
Automatic message from %%MAIL_SIGNATURE%%

P.S : the document has to be indexed by our machines. You can arrive on the page 'Document not accessible' by clicking on the link as long as the indexation has not processed your document.

<a href='%%MODIFY_PROFIL_URL%%'>I don't want to receive these emails anymore.</a>