%%MAIL_TO_FULLNAME%%,

A new document is online on HAL :
Un nouveau dépôt est en ligne sur HAL :
<a href='%%DOCUMENT_URL%%' style="color:#292063;">%%DOC_REF%%</a>

One of the author is affiliated to the structure %%STRUCTNAME%% that you administrate.

As administrator, you have the property rights on this document : you can complete the metadata, add a file or a new version.

Greatings,
--
Automatic message from %%MAIL_SIGNATURE%%

P.S : the document has to be indexed by our machines. You can arrive on the page 'Document not accessible' by clicking on the link as long as the indexation has not processed your document.

<a href='%%MODIFY_PROFIL_URL%%'>I don't want to receive this kind of emails anymore.</a>