Dear %%USER%%,

Please make the following corrections to your document %%DOC_ID%% (version %%DOC_VERSION%%) by login on %%PORTAIL%% ( %%PORTAIL_URL%% )
%%MSG_MODERATEUR%%

Without modifications or answer in the next 5 months, the document will be deleted from the server. You can user the feature "Annotate/Answer" to the modification request.

Greetings,

-----------------
The %%PORTAIL%%/CCSD team