Dear %%USER%%,

The information regarding your new record on %%PORTAIL%% ( %%PORTAIL_URL%% ) is :

%%DOC_REF%%
------------------------------------------------------------------------------
id : %%DOC_ID%%
version : %%DOC_VERSION%%
password : %%DOC_PWD%%
submission date : %%DOC_DATE%%
------------------------------------------------------------------------------

This information will be necessary during your futur modifications of this article.

Greetings,

-----------------
The %%PORTAIL%%/CCSD team