<style>

    .typdoc label.type {margin-top:0px; margin-bottom: 0px;}
    .type {margin: 0px;}

</style>

<script type='text/javascript'>
function show(e, f) {
	$('.btn-showing').removeClass('btn-danger').addClass('btn-success');
	$(e).removeClass('btn-success').addClass('btn-danger');
	$('.meta').hide();
	$('.meta').closest('tr').hide();
	$('.alert-info').hide();
	$('#' + f).show();
	$('#' + f).closest('tr').show();
	$('.alert-info').show();
}
</script>

<div class="row">
	<div class="col-md-6">
		<table class="table table-condensed table-hover typdoc">
            <thead>
                <tr>
                    <th width="10%"><h4><?php echo $this->translate('Catégorie')?></h4></th>
                    <th width="30%"><h4><?php echo $this->translate('Type')?></h4></th>
                </tr>
            </thead>
			<tbody>
    		<?php
            foreach ($this->typdocs as $typdoc) { ?>
				<tr>
			        <td>
				        <span class='category'>
			        	<?php echo $this->translate($typdoc['label'])?>
				        </span>
			        </td>
			        <td>
				        <?php 
				        if (isset($typdoc['children']) && is_array($typdoc['children'])) { ?>
				        <table width="100%">
		            	   <tbody>
		            			<?php 
							    foreach ($typdoc['children'] as $type) { ?>   
		                    		<tr>
		   		                        <td>
		                            		<div class="type">
		                                		<label>
				                                    <!-- >$type['id']-->
				                                    <span><?php echo $this->translate($type['label'])?></span>
		                                		</label>
		                            		</div>
		                        		</td>
		                        		<td width="5%">
				                            <button class='btn btn-xs btn-success btn-showing' onclick='show(this, "typdoc_<?php echo $type['id']; ?>");' style='float: right;'>Voir</button>
				                        </td>
		                    		</tr>
		                		<?php }?>
		                	</tbody>
		            	</table>        
						<?php } ?>
					</td>
					
				</tr>
			<?php } ?>
	    	</tbody>
        </table>
    </div>
    <div class="col-md-6">
    	<table class="table table-condensed table-hover typdoc">
            <thead>
                <tr>
                    <th><h4><?php echo $this->translate('Métadonnées')?></h4></th>
                </tr>
            </thead>
			<tbody>
			<?php
            foreach ($this->typdocs as $typdoc) { ?>
				<tr style='display: none;'>
					<td style='border-top: none;'>
						<?php 
				        if (isset($typdoc['children']) && is_array($typdoc['children'])) { 
							foreach ($typdoc['children'] as $type) {
							?>
					        <table class="meta" id='typdoc_<?php echo $type['id']; ?>' style='display: none;'>
			            	   <tbody>
			            			<?php 
										$ini = Hal_Ini::file_merge(array (DEFAULT_CONFIG_PATH . INSTANCEPREFIX . '/meta.ini' => $type['id'], SPACE . CONFIG . 'meta.ini' => $type['id']), array ('section_default' => 'metas'));
	
										$form = new Ccsd_Form();
								        $form->setAttrib('class', 'form-horizontal');
								        $form->setMethod('post');
								        $form->setAttrib('enctype', 'multipart/form-data');
								        $form->setOptions ($ini)->setName('HAL_SUBMIT');
								        $form->getElement('type')->setValue($type['id']);
								        
								        foreach ($form->getElements() as $element) {
											if ($element instanceof Zend_Form_SubForm ||
												$element instanceof Zend_Form_DisplayGroup ||
												$element instanceof Ccsd_Form_Element_Hidden ||
												$element instanceof Ccsd_Form_Element_Hr ||
												$element instanceof Zend_Form_Element_Button ||
												$element instanceof Ccsd_Form_Element_Invisible ||
												$element instanceof Ccsd_Form_Element_Hr ||
												$element instanceof Ccsd_Form_Element_Submit) continue;
										?>   
			                    		<tr>
			                    			<td width="20%" align="left" style="<?php echo $element->isRequired() ? "font-weight: bold" : "font-style: italic;" ?>"><?php echo $element->getName(); ?></td>
			   		                        <td width="30%" align="left" style="<?php echo $element->isRequired() ? "font-weight: bold" : "font-style: italic;" ?>"><?php echo $element->getLabel(); ?></td>
			   		                        <td align="center">
			   		                        	<?php 
			   		                        	echo $this->translate ($element->getType())
			   		                        	?>
			   		                        </td>
			                        		<td width="20%" align="right" style="<?php echo $element->isRequired() ? "font-weight: bold" : "font-style: italic;" ?>"><?php echo $element->isRequired() ? $this->translate("Obligatoire") : $this->translate("Optionnel"); ?></td>
			                    		</tr>
			                    		
			                    		<?php } ?>
			                	</tbody>
			            	</table>        
							<?php 
							}
						} else { ?>
						<!-- section metas -->
						<?php } ?>
					</td>
				</tr>
			<?php } ?>
            </tbody>
        </table>
        <div class='alert alert-info' style='display : none;'>
        <?php echo $this->translate("Attention : l'ajout d'un domaine est susceptible de modifier cette liste."); ?>
        </div>
    </div>
</div>