Bonjour %%USER%%,

Ce message automatique vous indique les nouveaux documents disponibles correspondant à votre alerte : %%ALERT_NAME%%
La fréquence de votre alerte est : %%ALERT_FREQ%%
Il y a %%ALERT_NUM_DOCS%% documents correspondant à votre critère d'abonnement.
Voici le lien pour accéder à votre recherche dans l'interface de HAL : %%ALERT_SEARCH_URL%%
Vous pouvez modifier vos alertes en ligne à l'adresse : https://hal.archives-ouvertes.fr/user/search

------------------------------------------------------------------------------
%%ALERT_DOC_LIST%%
------------------------------------------------------------------------------

Fin de la liste.

--
L'équipe %%PORTAIL%%/CCSD
