Bonjour %%USER%%,

Les informations concernant votre nouveau dépôt sur %%PORTAIL%% ( <a href="%%DOC_URL%%">%%DOC_URL%%</a> ) sont :

%%DOC_REF%%
------------------------------------------------------------------------------
identifiant : %%DOC_ID%%
version : %%DOC_VERSION%%
mot de passe : %%DOC_PWD%%
date de soumission : %%DOC_DATE%%
------------------------------------------------------------------------------

Ces informations vous seront nécessaires lors de vos éventuelles modifications sur cet article.

Ce document va maintenant être contrôlé : vérification du(des) fichier(s), saisie des métadonnées, etc...

Cordialement,

-----------------
L'équipe %%PORTAIL%%/CCSD