Bonjour %%USER%%,


Ce message est une relance, une action de votre part est requise.

Votre dépôt ne peut pas être mis en ligne en l'état.
Merci de bien vouloir apporter les corrections suivantes à ce document %%DOC_ID%%, version %%DOC_VERSION%% en vous connectant au portail HAL ( %%PORTAIL%%  %%PORTAIL_URL%% )

       titre     : %%DOC_TITLE%%

Informations données par le modérateur:
---
%%MSG_MODERATEUR%%
---
Apporter ces corrections en utilisant l'action "Modifier" ou "Répondre" dans l'espace "Documents en attente de modification" de la page Mes dépôts.

Cordialement,

-- 
L'équipe du portail %%PORTAIL%%
HAL CCSD