%%MAIL_TO_FULLNAME%%,

Vous avez été reconnu comme auteur d'un nouveau dépôt sur HAL :

<a href='%%DOCUMENT_URL%%' style="color:#292063;">%%DOC_REF%%</a>

Êtes vous bien auteur de ce document ? <a href='%%OWNERSHIP_KO_URL%%' style="border:solid #292063 1px; border-radius:4px; padding:2px; color:white; background-color: #292063;">NON</a>  <a href='%%OWNERSHIP_OK_URL%%' style="color:#292063;">OUI</a>

En tant qu'auteur de cette publication, vous avez les droits de propriété sur ce dépôt. Vous pouvez compléter les métadonnées, ajouter un fichier ou une nouvelle version.

Sincères salutations,
--
Message automatique du %%MAIL_SIGNATURE%%

<a href='%%MODIFY_PROFIL_URL%%'>Je ne souhaite plus recevoir ce type de mail.</a>