Bonjour %%USER%%,

Votre document %%DOC_ID%%, version %%DOC_VERSION%% est maintenant en ligne sur %%PORTAIL%% ( %%PORTAIL_URL%% ).

Le lien pour visualiser votre article est : %%DOC_URL%%.

Ce dépôt a été transféré sur arXiv et son identifiant arXiv définitif sera automatiquement ajouté à HAL dès que celui-ci sera validé par arXiv.

%%MSG_MODERATEUR%%

Cordialement,

-----------------
L'équipe %%PORTAIL%%/CCSD