Bonjour %%USER%%,

Les informations concernant votre nouvelle notice sur %%PORTAIL%% ( %%PORTAIL_URL%% ) sont :

%%DOC_REF%%
------------------------------------------------------------------------------
identifiant : %%DOC_ID%%
version : %%DOC_VERSION%%
mot de passe : %%DOC_PWD%%
date de soumission : %%DOC_DATE%%
------------------------------------------------------------------------------

Ces informations vous seront nécessaires lors de vos éventuelles modifications sur cet article.

Cordialement,

-----------------
L'équipe %%PORTAIL%%/CCSD