<div class="jumbotron">
    <h1>Mon CV/Mes publications</h1>
</div>
<p>HAL propose dans l'espace de chaque utilisateur connecté la fonctionnalité Mon CV/Mes publications : elle permet, au minimum, d'afficher dans une page et de façon dynamique la liste des  publications d'un auteur présentes dans HAL.</p>
<p>Pour disposer de cette fonctionnalité, il faut être auteur d'au moins une publication déposée dans HAL et avoir créé son identifiant auteur <b>idHAL</b>.</p>
<p>La page peut être complétée avec un titre, du texte libre, la photo issue du profil dans HAL, des données issues de l'IdHAL (ORCID, IdRef, compte twitter, adresse de blog, etc.) et d'autres extraites des dépôts : les disciplines, les mots-clés, les co-auteurs, les titres des revues, les années de publication, la participation à des projets ANR ou européens.</p>
<br/>
<p>Chaque CV a une url pérenne de type : <b>https://cv.archives-ouvertes.fr/idHAL</b></p>
<br/>
<p><a class="btn btn-primary btn-lg" href="https://doc.archives-ouvertes.fr/identifiant-auteur-idhal-cv/">Documentation en ligne</a>
