<div class="jumbotron">
    <h1>My CV / My publications</h1>
</div>
<p>Via your space HAL offers you the My CV / My publications feature.</p>
<p>This functionnality allows you to dynamically display in one page, the list of an author's publications hosted by HAL.</p>
<p>To use  this feature you must be the author of at least one publication and have created your idHAL identifier.</p>
<p>The page can be supplemented with a title, free text, your HAL picture, data from the IdHAL (ORCID , IdRef, twitter account , blog address, etc. ) and from your deposits (disciplines , keywords, co-authors, journal titles , years of publication, participation in ANR and European projects).</p>
<br />
<p>Each CV has a permanent URL as : <b>https://cv.archives-ouvertes.fr/idHAL</b></p>
<br />
<p><a class="btn btn-primary btn-lg" href="https://doc.archives-ouvertes.fr/en/author-identifier-idhal-and-cv/">Online documentation</a>
