<?php
/** @var @var Hal_View $this */
$years = $this->cv->getFacetProducedYear();
if (count($years)) {
    krsort($years);
    $listPrinc = $listSec = '';
    $count = 0;
    $filterYear = isset($filters['producedDateY_i']) && is_array($filters['producedDateY_i']) ? array_keys($filters['producedDateY_i']) : array();
    foreach ($years as $year => $nbdoc) {
        $link = $href;
        if (! in_array($year, $filterYear)) {
            $link .= '/producedDateY_i/' . $year;
        }

        $elem = '<li><a href="' . $link . '" >' . $year . ' <span class="badge badge-default">' . $nbdoc . '</span></a></li>';
        if ($count < 10) {
            $listPrinc .= $elem;
        } else {
            $listSec   .= $elem;
        }
        $count ++;
    }
    $content = '<div class="year">';
    $content .= '   <ul style="">' . $listPrinc . '</ul>';
    if ($listSec != '') {
        $content .= '   <div class="widget-footer"><a href="javascript:void(0);" onclick="displayDiv(this)">&#155; ' . $this->translate("Liste complète") . '</a></div>';
        $content .= '</div>';
        $content .= '<div class="year-list" style="display:none;">';
        $content .= '   <div class="overflow"><ul>' . $listPrinc . $listSec . '</ul></div>';
        $content .= '   <div class="widget-footer"><a href="javascript:void(0);" onclick="displayDiv(this)">&#155; ' . $this->translate("Liste principale") . '</a></div>';
    }
    $content .= '</div>';

    echo $this->widget(array('title' => $this->translate('cv_widget_years'), 'content' => $content, 'class' => 'widget-'.'years'));
}

