<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->document->getMainTitle(); ?></title>
    <?php
        $this->jQuery()->addJavascriptFile('https://cdn.jwplayer.com/libraries/jI7CRvpx.js');
        echo $this->jQuery()->setLocalPath(CCSDLIB . '/js/jquery/min.1.9.1.js')->enable();
    ?>
</head>

<body>
    <?php
    $options = [
        'title' => $this->document->getMainTitle(),
        'src' => $this->file->getPath(true)];
    ?>
    <div>
        <?php echo $this->jwplayer($options)->play(); ?>
    </div>
</body>

</html>