
<hr />
<div class="row">
    <div class="col-sm-4 col-md-4">
        <div class="thumbnail home-thumbnail">
            <img src="/img/halms-1-large.png" />
            <div class="caption">
                <h3><span class="step">1</span><?php echo $this->translate("Dépôt sur HAL"); ?></h3>
                <p><?php echo $this->translate("L'article  doit être déposé dans l'archive ouverte HAL"); ?></p>
            </div>
        </div>
    </div>

    <div class="col-sm-4 col-md-4">
        <div class="thumbnail home-thumbnail">
            <img src="/img/halms-2-large.png" />
            <div class="caption">
                <h3><span class="step">2</span><?php echo $this->translate("Vérification d'éligibilité"); ?></h3>
                <p><?php echo $this->translate("Le dépôt doit répondre au critère de transfert sur PubMed Central (discipline SDV, présence d'un  PMID)"); ?></p>
            </div>
        </div>
    </div>

    <div class="col-sm-4 col-md-4">
        <div class="thumbnail home-thumbnail">
            <img src="/img/halms-3-large.png" />
            <div class="caption">
                <h3><span class="step">3</span><?php echo $this->translate("Conversion en XML"); ?></h3>
                <p><?php echo $this->translate("L'article est converti en XML"); ?></p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-4 col-md-4">
        <div class="thumbnail home-thumbnail">
            <img src="/img/halms-4-large.png" />
            <div class="caption">
                <h3><span class="step">4</span><?php echo $this->translate("Validation par l'auteur"); ?></h3>
                <p><?php echo $this->translate("L'auteur valide la conversion XML de son dépôt"); ?></p>
            </div>
        </div>
    </div>

    <div class="col-sm-4 col-md-4">
        <div class="thumbnail home-thumbnail">
            <img src="/img/halms-5-large.png" />
            <div class="caption">
                <h3><span class="step">5</span><?php echo $this->translate("Transfert sur PubMed Central"); ?></h3>
                <p><?php echo $this->translate("Le dépôt est envoyé sur PubMed Central"); ?></p>
            </div>
        </div>
    </div>

    <div class="col-sm-4 col-md-4">
        <div class="thumbnail home-thumbnail">
            <img src="/img/halms-6-large.png" />
            <div class="caption">
                <h3><span class="step">6</span><?php echo $this->translate("Mise à jour dans HAL"); ?></h3>
                <p><?php echo $this->translate("L'article est mis à jour dans l'archive ouverte HAL (renseignement PMCID)"); ?></p>
            </div>
        </div>
    </div>

</div>


<?php /**
    <div class="well">
            <h4 class="list-group-item-heading halms-color"><strong>1 - </strong>&nbsp;<?php echo $this->translate("Dépôt dans l'archive ouverte HAL"); ?></h4>
            <p class="list-group-item-text"><?php echo $this->translate("L'article  doit être déposé dans l'archive ouverte HAL"); ?></p>
    </div>

    <div class="well">
            <h4 class="list-group-item-heading halms-color"><strong>2 - </strong>&nbsp;<?php echo $this->translate("Vérification de l'éligibilité du dépôt"); ?></h4>
            <p class="list-group-item-text"><?php echo $this->translate("Le dépôt doivt répondre au critère de transfert sur PubMed Central (discipline SDV, présence d'un  PMID)"); ?></p>
    </div>

    <div class="well">
            <h4 class="list-group-item-heading halms-color"><strong>3 - </strong>&nbsp;<?php echo $this->translate("Conversion du dépôt en XML"); ?></h4>
            <p class="list-group-item-text"><?php echo $this->translate("L'article est converti en XML"); ?></p>
    </div>

    <div class="well">
            <h4 class="list-group-item-heading halms-color"><strong>4 - </strong>&nbsp;<?php echo $this->translate("Validation par l'auteur"); ?></h4>
            <p class="list-group-item-text"><?php echo $this->translate("L'auteur valide la conversion XML de son dépôt"); ?></p>
    </div>

    <div class="well">
            <h4 class="list-group-item-heading halms-color"><strong>5 - </strong>&nbsp;<?php echo $this->translate("Transfert sur PubMed Central"); ?></h4>
            <p class="list-group-item-text"><?php echo $this->translate("Le dépôt est envoyé sur PubMed Central"); ?></p>
    </div>

    <div class="well">
            <h4 class="list-group-item-heading halms-color"><strong>6 - </strong>&nbsp;<?php echo $this->translate("Mise à jour du dépôt dans HAL"); ?></h4>
            <p class="list-group-item-text"><?php echo $this->translate("L'article est mis à jour dans l'archive ouverte HAL (renseignement PMCID)"); ?></p>
    </div>**/
