<div class="alert alert-block alert-error fade in">
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	<h4 class="alert-heading"><?php echo $this->translate("La collection que vous demandez n'existe pas !") ?></h4>
	<?php if (isset($this->description)){ ?>
		<p><?php echo $this->description; ?></p>
	<?php } ?>
	<p>&nbsp;</p>
	<p><a href="<?php echo PREFIX_URL?>" class="btn btn-danger"><?php echo $this->translate("Retourner à l'accueil");?></a></p>
</div>