<br>
<div class="jumbotron">
    <h2><?php echo $this->translate("Le document n'est pas indexé."); ?></h2>

    <?php
    $identifiant = $this->escape($this->documentIdentifier);
    $version = $this->escape($this->documentVersion);

    if ($version != 0) {
        $version = $this->translate('version %s', $version);
    } else {
        $version = '';
    }

    ?>
    <?php echo $this->translate("Le document avec l'identifiant <strong>%s</strong> <em>%s</em> n'est pas accessible.", [$identifiant, $version]); ?>
    <?php echo $this->translate("Il peut être en attente d'indexation, merci de ré-essayer dans quelques minutes."); ?>

    <hr>
    <a class="btn btn-primary" href="<?php echo $this->url(['controller' => 'search', 'action' => 'index']); ?>"
       role="button"><?php echo $this->translate('Rechercher un document'); ?></a>
</div>


