<?php
/**
* @var Hal_View $this
*/ ?>
<div class="alert alert-block alert-error fade in">
    <h4 class="alert-heading"><?php echo $this->translate($this->message); ?></h4>
    <?php if (isset($this->description)) : ?>
        <p><?php echo $this->translate($this->description); ?></p>
        <p></p>

    <?php endif; ?>
    <p><a href="/" class="btn btn-danger"><?php echo $this->translate("Retourner à l'accueil"); ?></a></p>
</div>

<?php if (isset($this->exception)) { ?>
    <?php if (ENV_TEST == APPLICATION_ENV || ENV_DEV == APPLICATION_ENV) { ?>
        <div class="debug">
            <?php if (isset($this->exception)) { ?>
                <h4><i class="icon-chevron-right active"></i> Exception</h4>
                <pre style="background:#fff;"><?php echo $this->exception->getMessage(); ?></pre>
            <?php } ?>

            <h4><i class="icon-chevron-right active"></i> Paramètres</h4>
            <pre style="background:#fff;"><?php if (isset($this->request)) {
                    echo $this->escape(var_export($this->request->getParams(), true));
                } ?></pre>

            <h4><i class="icon-chevron-right active"></i> Traces</h4>
            <pre style="background:#fff;"><?php echo $this->exception->getTraceAsString() ?></pre>
        </div>
        <?php

    } else {
        $text = 'Error: ' . $this->exception->getMessage();
        if (is_object($this->request)) {
            $text .= PHP_EOL . 'Dump: ' . Zend_Debug::dump($this->request->getParams(), null, false);
        }
        $text .= PHP_EOL . 'Stack Trace: ' . Zend_Debug::dump($this->exception->getTrace(), null, false);

        if (is_dir(EXCEPTIONS_LOG_PATH)) {
            $logFilename = EXCEPTIONS_LOG_PATH . SPACE_NAME . "_exceptions.log";
            error_log($text, 3, $logFilename);
            error_log($this->exception->getMessage(), 3, $logFilename);
        } else {
            error_log('PANIC: unable to log an exception into file ' . EXCEPTIONS_LOG_PATH . SPACE_NAME . "_exceptions.log");
        }



    }
    ?>
    <?php
}
