<!-- Modal -->
<div class="modal fade bottom in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">        <span class='label label-success'>
            <?php echo $this->translate($this->label); ?>
        </span>
        <span style='margin-left:15px; color: black;'>
            <strong><?php echo $this->translate("popup_" . $this->core); ?></strong>
        </span>
        </h4>
      </div>
      <div class="modal-body">
        <?php 

		/*$o = $this->form->getElement('TITRE');
        
        if ($o) {
			$o->setValue($this->term);
		}
		
		$o = $this->form->getElement('JNAME');
		
		if ($o) {
			$o->setValue($this->term);
		}*/
        

        echo $this->form; 
        ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="<?php echo $this->labelFct; ?>('<?php echo $this->core ?>', '<?php echo $this->element; ?>');"><?php echo $this->translate($this->labelSubmit); ?></button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->