<div class="alert alert-block alert-error fade in">
	<h4 class="alert-heading"><?php echo $this->translate($this->message); ?></h4>
	<?php if (isset($this->description)) : ?>
		<p><?php echo $this->translate($this->description); ?></p>
		<p></p>

	<?php endif; ?>
	<p><a href="/" class="btn btn-danger"><?php echo $this->translate("Retourner à l'accueil"); ?></a></p>
</div>

<?php if (isset($this->exception)){ ?>
    <?php if (true) {  ?>
    <div class="debug">
		<?php if (isset($this->exception)){ ?>
			<h4><i class="icon-chevron-right active"></i> Exception</h4>
			<pre style="background:#fff;"><?php echo $this->exception->getMessage(); ?></pre>
		<?php } ?>

		<h4><i class="icon-chevron-right active"></i> Paramètres</h4>
		<pre style="background:#fff;"><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>

		<h4><i class="icon-chevron-right active"></i> Traces</h4>
		<pre style="background:#fff;"><?php echo $this->exception->getTraceAsString() ?></pre>
	</div>
    <?php } else {
        $mail = new Zend_Mail();
        $text = 'Error: '.$this->exception->getMessage();
        $text .= '<br /><br />Dump: '.Zend_Debug::dump($this->request->getParams(), null, false);
        $text .= '<br /><br />Stack Trace: '.Zend_Debug::dump($this->exception->getTrace(), null, false);
        $mail->setBodyHtml($text);
        $mail->setFrom('ccsd-tech@ccsd.cnrs.fr');
        $mail->addTo('ccsd-tech@ccsd.cnrs.fr');
        $mail->setSubject('[HALMS PHP Error]  - ' .  $this->exception->getMessage());
        $mail->send();
    } ?>
<?php }
