<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Un outil pour tester. Quelles sont les publications déposées dans HAL qui apparaîtront
            dans votre fiche CRAC
            cette année ?</h3>
    </div>
    <div class="panel-body">
        <p>La fiche CRAC est automatiquement alimentée par les publications déposées dans HAL (références
            bibliographiques et dépôts avec fichier).</p>
        <p>L'application CRAC utilise des requêtes API fournies par l'équipe du CCSD que vous pouvez tester avec cet
            outil.</p>
        <p>En vous connectant à HAL, le formulaire est automatiquement renseigné avec vos prénom et nom. La connexion
            est facultative.</p>


        <p>Si toutes vos publications correspondant aux dates de cette campagne 2018-2019 ne sont pas dans HAL, pensez à
            les <a
                    class="btn btn-default btn-xs" href="/submit"><span class="glyphicon glyphicon-plus"
                                                                        aria-hidden="true"></span>&nbsp;ajouter</a>.</p>

        <p><strong>Déposer dans HAL</strong></p>
        <p>L'équipe support du CCSD propose des séances de <strong>formation en ligne d'une heure</strong>. <a
                    class="btn btn-default btn-xs" target="_blank" title="Webinaire"
                    rel="noopener" href="https://zoom.us/webinar/register/WN_ASt8_Ma0TgOzgHEAQWWeKA"><span
                        class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp;Inscription/En savoir plus</a>
        </p>

        <p class="text-info"><strong><a target="_blank" rel="noopener"
                    href="https://doc.archives-ouvertes.fr/guide_utilisateurs/depots-hal-et-fiche-crac-faq/">FAQ Dépôts
                HAL et fiche CRAC</a></strong></p>

    </div>

    <div class="panel-footer">Si vous constatez des incohérences entre ce que vous avez déposé dans HAL et la liste,
        merci de nous le signaler à hal.support [at@] ccsd.cnrs.fr
    </div>

</div>