<?php
$critere = Zend_Controller_Front::getInstance()->getRequest()->getParam('critere');
$category = Zend_Controller_Front::getInstance()->getRequest()->getParam('category');
$critere = $this->escape($critere);

?>

<form method='get' action='<?php echo URL . '/' . $this->controllerName . "/browse" ?>'>

    <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
        <input type="text" class="form-control" name="critere" value="<?php echo Ccsd_Tools::ifsetor($critere, ''); ?>">
    </div>

    <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
        <select name="category" class="form-control">
            <?php foreach (['*', 'regroupinstitution', 'institution', 'regrouplaboratory', 'laboratory', 'department', 'researchteam'] as $v) {
                echo "<option value='$v' " . ($category == $v ? "selected='selected'" : "") . ">";
                if ($v == "*") {
                    echo $this->translate("Tout type de structure");
                } else {
                    echo $this->translate($v);
                }
                echo "</option>";
            } ?>
        </select>
    </div>

    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <button class='btn btn-primary'><?php echo $this->translate("Rechercher") ?></button>
    </div>

</form>