<?php
/**
 * Formulaire de modification de mot de passe
 */

$this->layout()->pageTitle = $this->translate("Changer le mot de passe de votre compte CCSD");
$this->layout()->pageTitle = $this->layout()->pageTitle;

$this->layout()->pageDescription = $this->translate('Changement de mot de passe');

if ($this->resultMessage) {
    echo $this->resultMessage;
}

?>

<?php 

if ($this->form) {
    echo $this->form;
}

?>

<?php 