<?php
/**
 * @var Hal_View $this
 * @var Hal_View_Helper_Layout $layout
 * Formulaire de modification de mot de passe
 */

$layout = $this->layout();
$layout->pageTitle = $this->translate("Changer le mot de passe de votre compte CCSD");
$layout->pageDescription = $this->translate('Changement de mot de passe');

if ($this->resultMessage) {
    echo $this->resultMessage;
}

if ($this->form) {
    echo $this->form;
}
