<?php
/** @var Hal_View $this */
$this->layout()->pageDescription = $this->translate("Liste de mes collections");

if ($this->collections == 'all') { ?>
	<div class="alert fade in">
            <button type="button" class="close" data-dismiss="alert">×</button>
			<strong><?php echo $this->translate('Gestionnaire de toutes les collections')?></strong>
    </div>
<?php } else { ?>
    <?php if ($this->search) {?>
        <form action="/user/collections" method="post" id="form-collection-list">
            <div class="form-actions">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="input-group">
                            <input type="text" class="form-control" name="q" value="<?php echo $this->q ?>" id="q" autocomplete="off"/>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="icon glyphicon glyphicon-search"></i>&nbsp;<?php echo $this->translate('Rechercher') ?>
                        </button>
                    </span>
                        </div>
                    </div>

                </div>
            </div>
        </form>
        <script type="text/javascript">
            $(document).ready(function(){
                $('#q').autocomplete({
                    minLength: 2,
                    html: true,
                    source: "/user/ajaxsearchcollection",
                    select: function( event, ui ) {
                        link('/user/collections/sid/' + ui.item.id);
                    }
                });
            });
        </script>
    <?php } ?>
	<?php if (count($this->collections)) { ?>
        <table class="table table-striped table-hover" width="100%">
            <thead>
                <tr>
                    <th width="140"></th>
                    <th><?php echo $this->translate('Nom')?></th>
                    <th class="text-right"><?php echo $this->translate('Actions')?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->collections as $collection) {?>
                    <tr>
                        <td style="text-align: center; vertical-align: middle;"><i class="glyphicon glyphicon-tag" style="font-size: 30px;line-height:70px;"></i></td>
                        <td>
                            <h4><?php echo $collection->getShortname();?><small> - <?php echo $collection->getFullname();?></small></h4>
                            <blockquote><?php echo $this->translate('Mode')?> : <?php echo ($collection->getMode() == Hal_Site_Settings_Collection::MODE_AUTO ? '<span class="label label-success">' . $this->translate($collection->getMode()) . '</span>' : $this->translate($collection->getMode())) ?><br />
                                <?php $critere = Hal_Site_Collection::getFullCritere($collection->getSid());
                                if ($critere != '') { ?>
                                    <small><?php echo $this->translate('Critère')?> : <?php echo $critere;?></small>
                                <?php } ?>
                            </blockquote>
                        </td>
                        <td align="right" class="middle">
                            <a href="/user/collections/tampid/<?php echo $collection->getShortname(); ?>" data-toggle="tooltip" title="<?php echo $this->translate('Gérer')?>"><i class="glyphicon glyphicon-wrench"></i></a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    <?php } ?>
<?php } ?>