<?php
$this->layout ()->pageTitle = $this->translate ( "Mot de passe oublié ?" );



if ($this->form) {
	$this->layout ()->pageDescription = $this->translate ( "Saisissez votre nom d'utilisateur. Nous vous enverrons un courriel avec un lien vers une page où vous pourrez facilement créer un nouveau mot de passe." );
	echo $this->form;
} else {
	echo $this->DisplayFlashMessages('success', false);
}
