
<div class="col-md-12">
	<ul class="pagination">
<?php
$browseParams = array();
$browseParams ['controller'] = Zend_Controller_Front::getInstance ()->getRequest ()->getControllerName ();
$browseParams ['action'] = Zend_Controller_Front::getInstance ()->getRequest ()->getUserParam ( 'action' );

$letterValues = range ( 'A', 'Z' );
$letterValues [] = 'other';
$letterValues [] = 'all';

$browseTypes = array (
		'file' => 'file',
		'notice' => 'notice',
		'annex' => 'annex'
);

if (! array_key_exists ( $this->typeFilter, $browseTypes )) {
	$browseParams ['submitType_s'] = null;
} else {
	$browseParams ['submitType_s'] = $this->typeFilter;
}

if ($browseParams ['submitType_s'] == null) {
	unset ( $browseParams ['submitType_s'] );
}

/**
 * Tri des facettes
 */
if (! array_key_exists ( $this->sortType, Hal_Settings_Search::$facetSortingTypeIconsClass )) {
	$browseParams ['sort'] = Hal_Settings_Search::$defaultFacetSortingType;
} else {
	$browseParams ['sort'] = $this->sortType;
}

/**
 * // Tri des facettes
 */

foreach ( $letterValues as $char ) {
	$browseParams ['letter'] = $char;
	$url = $this->url ( $browseParams, null, TRUE );

	if ($this->letter == $char) {
		echo '<li class="active">';
	} else {
		echo '<li>';
	}

	echo '<a href="' . $this->escape ( $url ) . '">';
	switch ($char) {
		case 'other' :
		case 'all' :
			echo $this->translate ( $char );
			break;
		default :
			echo $char;
			break;
	}
	echo '</a>';
	echo '</li>';
}

?>
</ul>
</div>