<?php

$sortDataForView['score desc'] = '<span class="glyphicon glyphicon-sort-by-attributes-alt pull-left"></span>&nbsp;' . $this->translate('Pertinence');

$sortDataForView['auth_sort asc'] = '<span class="glyphicon glyphicon-user pull-left"></span>&nbsp;' . $this->translate('Auteur A&rarr;Z');
$sortDataForView['auth_sort desc'] = '<span class="glyphicon glyphicon-user pull-left"></span>&nbsp;' . $this->translate('Auteur Z&rarr;A');

$sortDataForView['title_sort asc'] = '<span class="glyphicon glyphicon-sort-by-alphabet pull-left"></span>&nbsp;' . $this->translate('Titre A&rarr;Z');
$sortDataForView['title_sort desc'] = '<span class="glyphicon glyphicon-sort-by-alphabet-alt pull-left" ></span>&nbsp;' . $this->translate('Titre Z&rarr;A');

$sortDataForView['producedDate_tdate asc'] = '<span class="glyphicon glyphicon-sort-by-order pull-left"></span>&nbsp;' . $this->translate('Date de publication croissante');
$sortDataForView['producedDate_tdate desc'] = '<span class="glyphicon glyphicon-sort-by-order-alt pull-left"></span>&nbsp;' . $this->translate('Date de publication décroissante');

$sortDataForView['submittedDate_tdate asc'] = '<span class="glyphicon glyphicon-sort-by-order pull-left"></span>&nbsp;' . $this->translate('Date de dépôt croissante');
$sortDataForView['submittedDate_tdate desc'] = '<span class="glyphicon glyphicon-sort-by-order-alt pull-left"></span>&nbsp;' . $this->translate('Date de dépôt décroissante');
?>

        <div class="btn-group">
        <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-sort"></span> <?php echo $this->translate('Tri'); ?> <span class="caret"></span>
        </button>
 <ul class="dropdown-menu" role="menu">
    <?php
    $urlParams = $this->parsedSearchParams;

    foreach ($sortDataForView as $sortType => $sortLabel) {
        $isActive = '';
        if (isset($this->parsedSearchParams['sort']) and ($this->parsedSearchParams['sort'] == $sortType)) {
            $isActive = ' btn-primary active disabled';
        } elseif (! isset($this->parsedSearchParams['sort']) and ($sortType == 'score desc')) {
            $isActive = ' btn-primary active disabled';
        } else {
            $urlParams['sort'] = $sortType;
        }



        echo '<li>';
        echo '<a rel="nofollow" href="';
        echo $this->escape($this->searchUrl($urlParams, null, TRUE, true, $this->searchType));
        echo '" class="btn btn-sm' . $isActive . '">';
        echo $this->translate($sortLabel);
        echo '</a>';
        echo '</li>';
    }

    ?>
                </ul>
        </div>