<?php 
//Profileur db (requetes sur la page)
$profileur = Zend_Db_Table_Abstract::getDefaultAdapter()->getProfiler();
$viewDbProfiler = $profileur->getEnabled();
$profileurBiblio = Hal_Db_Adapter_ReferenceBiblio::getAdapter()->getProfiler();
$viewDbProfilerBiblio = $profileurBiblio->getEnabled();
?>
<div class="debug">
	<p></p>
	<ul class="nav nav-tabs" id="debugTab">
	  <?php if ($viewDbProfiler) {?>
	  	<li><a href="#query" data-toggle="tab"><i class="glyphicon glyphglyphicon glyphicon-list-alt"></i> Query Profiler</a></li>
	  <?php }?>
	  <li><a href="#site" data-toggle="tab"><i class="glyphicon glyphglyphicon glyphicon-info-sign"></i> Site</a></li>
	  <li><a href="#user" data-toggle="tab"><i class="glyphicon glyphglyphicon glyphicon-user"></i> Utilisateur</a></li>
	</ul>
	
	<div class="tab-content">
		<?php if ($viewDbProfiler || $viewDbProfilerBiblio) {
		?>
		<div class="tab-pane" id="query">
		<?php
		if ($viewDbProfiler){
		$dbconfig = Zend_Db_Table_Abstract::getDefaultAdapter()->getConfig();
		?>
	    
	    	<blockquote>Hôte : <b><?php echo $dbconfig['host'];?></b><br />Base de données : <b><?php echo $dbconfig['dbname'];?></b><br />Nombre de requêtes : <b><?php echo $profileur->getTotalNumQueries()?></b><br />Temps total : <b><?php echo $profileur->getTotalElapsedSecs()?> (sec)</b>
	    	</blockquote>
	    	<table class="table table-hover table-striped">
	    		<thead>
					<tr>
	  					<th><i class="glyphicon glyphglyphicon glyphicon-tasks active"></i> Requêtes</th>
						<th width="40px"><i class="glyphicon glyphglyphicon glyphicon-time active"></i> Temps (sec.)</th>
					</tr>
				</thead>
	    		<tbody>
					<?php foreach ($profileur->getQueryProfiles() as $query) { ?>
						<tr>
							<td><small><?php echo $query->getQuery();?></small></td>
							<td align="right"><?php echo $query->getElapsedSecs();?></td>
						</tr>
					<?php }?>
				</tbody>
	    	</table>
			<?php 
		}
		if ($viewDbProfilerBiblio && $profileurBiblio->getQueryProfiles()!==false ){
			$dbconfig = Hal_Db_Adapter_ReferenceBiblio::getAdapter()->getConfig();
			?>
			
				<blockquote>Hôte : <b><?php echo $dbconfig['host'];?></b><br />Base de données : <b><?php echo $dbconfig['dbname'];?></b><br />Nombre de requêtes : <b><?php echo $profileurBiblio->getTotalNumQueries()?></b><br />Temps total : <b><?php echo $profileurBiblio->getTotalElapsedSecs()?> (sec)</b>
				</blockquote>
				<table class="table table-hover table-striped">
					<thead>
						<tr>
							  <th><i class="glyphicon glyphglyphicon glyphicon-tasks active"></i> Requêtes</th>
							<th width="40px"><i class="glyphicon glyphglyphicon glyphicon-time active"></i> Temps (sec.)</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($profileurBiblio->getQueryProfiles() as $query) { ?>
							<tr>
								<td><small><?php echo $query->getQuery();?></small></td>
								<td align="right"><?php echo $query->getElapsedSecs();?></td>
							</tr>
						<?php }?>
					</tbody>
				</table>
				<?php 
			}
			?>
		</div>
	<?php } 
	
	//Debug de l'environnement de la page
	?>
	<div class="tab-pane" id="site">
		<blockquote>Portail : <b><?php echo PORTAIL;?></b><br />	
		<?php if (defined('COLLECTION')) {?>
		Collection : <b><?php echo COLLECTION;?></b><br />
		<?php }?>
		SPACE_URL : <b><?php echo SPACE_URL;?></b><br />	
		DEFAULT_SPACE_URL : <b><?php echo DEFAULT_SPACE_URL;?></b><br />	
		PREFIX_URL : <b><?php echo PREFIX_URL;?></b><br />	
		</blockquote>
	</div>
	<div class="tab-pane" id="user">
		<blockquote><?php if (Hal_Auth::isLogged()) {?>Nom : <b><?php echo Hal_Auth::getInstance()->getIdentity()->getFullName();?></b><br />	
		UID : <b><?php echo Hal_Auth::getInstance()->getIdentity()->getUid();?></b><br />	
		<?php } else { ?>
		Non connecté
		<?php }?>
		</blockquote>
	</div>
	</div>
</div>

<script>
  $(function () {
    $('#debugTab a:first').tab('show');
  })
</script>