<div class="alert alert-block alert-error fade in">
	<button data-dismiss="alert" class="close" type="button">×</button>
    <h4 class="alert-heading">Erreur de connexion</h4>
    <p>Change this and that and try again. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum.</p><p>
    <a href="/" class="btn btn-danger">Retourner à l'accueil</a> 
    </p>
</div>