<?php if (is_file(SPACE . LAYOUT . 'footer.' . Zend_Registry::get('lang') . '.html')) { //Footer prédéfini ?>
    <div class="footer">
        <?php echo file_get_contents(SPACE . LAYOUT . 'footer.' . Zend_Registry::get('lang') . '.html'); ?>
    </div>
<?php } else { ?>
    <div class="footer footer-default row">
        <div class="footer-contact footer-col col-md-1">
            <h4><?php echo $this->translate('Contact'); ?></h4>
            <ul class="list-unstyled">
                <li><?php echo Hal_Tools::encryptMail('hal.support@ccsd.cnrs.fr'); ?></li>
                <li><a href="//support.ccsd.cnrs.fr/" target="_blank" rel="noopener">support.ccsd.cnrs.fr</a></li>
            </ul>
        </div>
        <div class="footer-infos footer-col col-md-1">
            <h4><?php echo $this->translate('Informations'); ?></h4>
            <ul class="list-unstyled">
                <li><a title="<?php echo $this->translate('RGPD'); ?>"
                       href="/view/privacy"><?php echo $this->translate('Données personnelles'); ?></a></li>
                <li><a href="/view/legalnotice"><?php echo $this->translate('Mentions légales'); ?></a></li>
                <li><a href="/view/conformiteRgaa"><?php echo $this->translate('Conformité RGAA'); ?></a></li>
                <li><a href="/view/accessibilityHelp"><?php echo $this->translate('Accessibilité'); ?></a></li>
            </ul>
        </div>
        <div class="footer-ccsd align-items-end col-12 col-md-offset-10">
            <a href="//www.ccsd.cnrs.fr/" target="_blank" rel="noopener"><img src="/img/logo-ccsd-footer.jpg" border="0"
                                                                         width="200" alt="CCSD"/></a>
        </div>
    </div>
<?php }
