<?php if (is_file(SPACE . LAYOUT . 'footer.' . Zend_Registry::get('lang') . '.html')) { //Footer prédéfini ?>
    <div class="footer">
        <?php echo file_get_contents(SPACE . LAYOUT . 'footer.' . Zend_Registry::get('lang') . '.html'); ?>
    </div>
<?php } else { ?>
    <div class="footer footer-default">
        <div class="footer-contact">
            <h4><?php echo $this->translate('Contact'); ?></h4>
            <a href="//support.ccsd.cnrs.fr/" target="_blank" rel="noopener">support.ccsd.cnrs.fr</a><br />
            <a href="mailto:hal.support@ccsd.cnrs.fr" onclick="this.target='_blank'">hal.support@ccsd.cnrs.fr</a>
        </div>
        <div class="footer-ccsd">
            <a href="//ccsd.cnrs.fr" target="_blank" rel="noopener"><img src="/img/logo-ccsd-footer.jpg" border="0" width="200" alt="Logo CCSD" /></a>
        </div>
    </div>
<?php }
