<ul class="nav navbar-nav navbar-right">
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">


				<img class="user-photo-thumb" alt="Photo de l'utilisateur" src="<?php echo  CV_URL . '/photo/' . Hal_Auth::getUid(). '/thumb?v=' . time(); ?>" style="width:16px;"/>


			&nbsp;<?php echo Hal_Auth::getScreenName(); ?>
		 	<b class="caret"></b>
		 </a>
		 <ul class="dropdown-menu pull-right">
			<li style="padding:0 10px;">
				<table width="350px" cellpadding="5" cellspacing="5">
		            <tr>

		                	<td width="110px;"><a href="<?php echo PREFIX_URL?>user"><img src="<?php echo  CV_URL . '/photo/' . Hal_Auth::getUid() . '/normal?v=' . time(); ?>" class="user-photo-normal img-thumbnail"/></a></td>
		                	<td class="text-left">

		                	<strong><?php echo Hal_Auth::getScreenName(); ?></strong><br />
		                	<i><?php echo Hal_Auth::getInstance()->getIdentity()->getEMail(); ?></i><br />
		                	<a href="/user" class="btn btn-primary btn-xs" style="margin-bottom:6px;"><?php echo $this->translate("Mon profil") ?></a><br />
		                	<a href="/user/changepassword" class="btn btn-primary btn-xs"><?php echo $this->translate("Modifier mon mot de passe") ?></a>
		                </td>
		            </tr>
	            	<?php $roles = Hal_Auth::getRoles();
                    if (! (count($roles) == 1 && $roles[0] == Hal_Acl::ROLE_MEMBER)) {?>
                    <tr>
						<td colspan="2">
							<span class="nav-header"><?php echo $this->translate("Privilèges") ?></span>
							<?php foreach ($roles as $rightId ) {?>
        						<span class="label label-danger"><?php echo $this->translate($rightId);?></span>
    						<?php }?>
						</td>
					</tr>
                    <?php } ?>
				</table>
			</li>
			<li class="divider"></li>
			<li style="padding:0 10px 10px; text-align:center;">
					<span><a href="<?php echo PREFIX_URL?>user/logout" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-off"></span>&nbsp;<?php echo $this->translate("Déconnexion") ?></a></span>
			</li>
		</ul>
	</li>
</ul>