<div class="footer">
    <div class="footer-contact">
        <h4><?php echo $this->translate('Contact'); ?></h4>
        <ul class="list-unstyled">
            <li><?php echo Hal_Tools::encryptMail('hal.support@ccsd.cnrs.fr'); ?></li>
            <li><a href="//support.ccsd.cnrs.fr/" target="_blank" rel="noopener">support.ccsd.cnrs.fr</a></li>
            <li><a title="<?php echo $this->translate('RGPD'); ?>"
                   href="/view/privacy"><?php echo $this->translate('Données personnelles'); ?></a></li>
            <li><a href="/view/legalnotice"><?php echo $this->translate('Mentions légales'); ?></a></li>
        </ul>
    </div>
    <div class="footer-ccsd">
        <a href="//www.ccsd.cnrs.fr/" target="_blank" rel="noopener"><img src="/img/logo-ccsd-footer.jpg" border="0"
                                                                     width="200" alt="CCSD"/></a>
    </div>
</div>