<div class="footer">
	<div class="footer-contact">
        <h4><?php echo $this->translate('Contact'); ?></h4>
        <a href="//support.ccsd.cnrs.fr/" target="_blank">support.ccsd.cnrs.fr</a><br />
        <a href="mailto:hal.support@ccsd.cnrs.fr" target="_blank">hal.support@ccsd.cnrs.fr</a>
	</div>
    <div class="footer-ccsd">
        <a href="//ccsd.cnrs.fr" target="_blank"><img src="/img/logo-ccsd-footer.jpg" border="0" width="200" alt="Logo Ccsd" /></a>
    </div>
</div>